/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 5.4.0-6ubuntu1~16.04.4 -O2 -fstack-protector-strong -fPIC -Os) */
`include "./CMOS/cmos_cells.v"

module byte_unstripping(data_unstripped, valid_unstripped, clk_2f, reset_L, data_par_0, data_par_1, valid_par_0, valid_par_1);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  input clk_2f;
  input [7:0] data_par_0;
  input [7:0] data_par_1;
  output [7:0] data_unstripped;
  wire lectura;
  input reset_L;
  wire selector;
  input valid_par_0;
  input valid_par_1;
  output valid_unstripped;
  NAND _050_ (
    .A(reset_L),
    .B(lectura),
    .Y(_002_)
  );
  NOR _051_ (
    .A(_002_),
    .B(selector),
    .Y(_001_)
  );
  NOT _052_ (
    .A(valid_par_1),
    .Y(_003_)
  );
  NOT _053_ (
    .A(selector),
    .Y(_004_)
  );
  NOR _054_ (
    .A(_004_),
    .B(_003_),
    .Y(_005_)
  );
  NOT _055_ (
    .A(valid_par_0),
    .Y(_006_)
  );
  NOR _056_ (
    .A(selector),
    .B(_006_),
    .Y(_007_)
  );
  NOR _057_ (
    .A(_007_),
    .B(_005_),
    .Y(_008_)
  );
  NOR _058_ (
    .A(_008_),
    .B(_002_),
    .Y(valid_unstripped)
  );
  NOT _059_ (
    .A(data_par_1[0]),
    .Y(_009_)
  );
  NOR _060_ (
    .A(_009_),
    .B(_004_),
    .Y(_010_)
  );
  NOT _061_ (
    .A(data_par_0[0]),
    .Y(_011_)
  );
  NOR _062_ (
    .A(_011_),
    .B(selector),
    .Y(_012_)
  );
  NOR _063_ (
    .A(_012_),
    .B(_010_),
    .Y(_013_)
  );
  NOR _064_ (
    .A(_013_),
    .B(_002_),
    .Y(data_unstripped[0])
  );
  NOT _065_ (
    .A(data_par_1[1]),
    .Y(_014_)
  );
  NOR _066_ (
    .A(_014_),
    .B(_004_),
    .Y(_015_)
  );
  NOT _067_ (
    .A(data_par_0[1]),
    .Y(_016_)
  );
  NOR _068_ (
    .A(_016_),
    .B(selector),
    .Y(_017_)
  );
  NOR _069_ (
    .A(_017_),
    .B(_015_),
    .Y(_018_)
  );
  NOR _070_ (
    .A(_018_),
    .B(_002_),
    .Y(data_unstripped[1])
  );
  NOT _071_ (
    .A(data_par_1[2]),
    .Y(_019_)
  );
  NOR _072_ (
    .A(_019_),
    .B(_004_),
    .Y(_020_)
  );
  NOT _073_ (
    .A(data_par_0[2]),
    .Y(_021_)
  );
  NOR _074_ (
    .A(_021_),
    .B(selector),
    .Y(_022_)
  );
  NOR _075_ (
    .A(_022_),
    .B(_020_),
    .Y(_023_)
  );
  NOR _076_ (
    .A(_023_),
    .B(_002_),
    .Y(data_unstripped[2])
  );
  NOT _077_ (
    .A(data_par_1[3]),
    .Y(_024_)
  );
  NOR _078_ (
    .A(_024_),
    .B(_004_),
    .Y(_025_)
  );
  NOT _079_ (
    .A(data_par_0[3]),
    .Y(_026_)
  );
  NOR _080_ (
    .A(_026_),
    .B(selector),
    .Y(_027_)
  );
  NOR _081_ (
    .A(_027_),
    .B(_025_),
    .Y(_028_)
  );
  NOR _082_ (
    .A(_028_),
    .B(_002_),
    .Y(data_unstripped[3])
  );
  NOT _083_ (
    .A(data_par_1[4]),
    .Y(_029_)
  );
  NOR _084_ (
    .A(_029_),
    .B(_004_),
    .Y(_030_)
  );
  NOT _085_ (
    .A(data_par_0[4]),
    .Y(_031_)
  );
  NOR _086_ (
    .A(_031_),
    .B(selector),
    .Y(_032_)
  );
  NOR _087_ (
    .A(_032_),
    .B(_030_),
    .Y(_033_)
  );
  NOR _088_ (
    .A(_033_),
    .B(_002_),
    .Y(data_unstripped[4])
  );
  NOT _089_ (
    .A(data_par_1[5]),
    .Y(_034_)
  );
  NOR _090_ (
    .A(_034_),
    .B(_004_),
    .Y(_035_)
  );
  NOT _091_ (
    .A(data_par_0[5]),
    .Y(_036_)
  );
  NOR _092_ (
    .A(_036_),
    .B(selector),
    .Y(_037_)
  );
  NOR _093_ (
    .A(_037_),
    .B(_035_),
    .Y(_038_)
  );
  NOR _094_ (
    .A(_038_),
    .B(_002_),
    .Y(data_unstripped[5])
  );
  NOT _095_ (
    .A(data_par_1[6]),
    .Y(_039_)
  );
  NOR _096_ (
    .A(_039_),
    .B(_004_),
    .Y(_040_)
  );
  NOT _097_ (
    .A(data_par_0[6]),
    .Y(_041_)
  );
  NOR _098_ (
    .A(_041_),
    .B(selector),
    .Y(_042_)
  );
  NOR _099_ (
    .A(_042_),
    .B(_040_),
    .Y(_043_)
  );
  NOR _100_ (
    .A(_043_),
    .B(_002_),
    .Y(data_unstripped[6])
  );
  NOT _101_ (
    .A(data_par_1[7]),
    .Y(_044_)
  );
  NOR _102_ (
    .A(_044_),
    .B(_004_),
    .Y(_045_)
  );
  NOT _103_ (
    .A(data_par_0[7]),
    .Y(_046_)
  );
  NOR _104_ (
    .A(_046_),
    .B(selector),
    .Y(_047_)
  );
  NOR _105_ (
    .A(_047_),
    .B(_045_),
    .Y(_048_)
  );
  NOR _106_ (
    .A(_048_),
    .B(_002_),
    .Y(data_unstripped[7])
  );
  NOT _107_ (
    .A(reset_L),
    .Y(_049_)
  );
  NOR _108_ (
    .A(_006_),
    .B(_049_),
    .Y(_000_)
  );
  DFF _109_ (
    .C(clk_2f),
    .D(_001_),
    .Q(selector)
  );
  DFF _110_ (
    .C(clk_2f),
    .D(_000_),
    .Q(lectura)
  );
endmodule

module demux(data_demux_0, data_demux_1, valid_demux_0, valid_demux_1, valid_unstripped, clk_2f, reset_L, data_unstripped);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  input clk_2f;
  output [7:0] data_demux_0;
  output [7:0] data_demux_1;
  wire [7:0] data_reg0;
  input [7:0] data_unstripped;
  input reset_L;
  output valid_demux_0;
  output valid_demux_1;
  input valid_unstripped;
  NOT _34_ (
    .A(valid_unstripped),
    .Y(_00_)
  );
  NOT _35_ (
    .A(reset_L),
    .Y(_01_)
  );
  NOR _36_ (
    .A(_01_),
    .B(_00_),
    .Y(valid_demux_0)
  );
  NOR _37_ (
    .A(data_reg0[0]),
    .B(valid_unstripped),
    .Y(_02_)
  );
  NOT _38_ (
    .A(data_unstripped[0]),
    .Y(_03_)
  );
  NAND _39_ (
    .A(_03_),
    .B(valid_unstripped),
    .Y(_04_)
  );
  NAND _40_ (
    .A(_04_),
    .B(reset_L),
    .Y(_05_)
  );
  NOR _41_ (
    .A(_05_),
    .B(_02_),
    .Y(data_demux_0[0])
  );
  NOR _42_ (
    .A(valid_unstripped),
    .B(data_reg0[1]),
    .Y(_06_)
  );
  NOT _43_ (
    .A(data_unstripped[1]),
    .Y(_07_)
  );
  NAND _44_ (
    .A(valid_unstripped),
    .B(_07_),
    .Y(_08_)
  );
  NAND _45_ (
    .A(_08_),
    .B(reset_L),
    .Y(_09_)
  );
  NOR _46_ (
    .A(_09_),
    .B(_06_),
    .Y(data_demux_0[1])
  );
  NOR _47_ (
    .A(data_reg0[2]),
    .B(valid_unstripped),
    .Y(_10_)
  );
  NOT _48_ (
    .A(data_unstripped[2]),
    .Y(_11_)
  );
  NAND _49_ (
    .A(_11_),
    .B(valid_unstripped),
    .Y(_12_)
  );
  NAND _50_ (
    .A(_12_),
    .B(reset_L),
    .Y(_13_)
  );
  NOR _51_ (
    .A(_13_),
    .B(_10_),
    .Y(data_demux_0[2])
  );
  NOR _52_ (
    .A(data_reg0[3]),
    .B(valid_unstripped),
    .Y(_14_)
  );
  NOT _53_ (
    .A(data_unstripped[3]),
    .Y(_15_)
  );
  NAND _54_ (
    .A(_15_),
    .B(valid_unstripped),
    .Y(_16_)
  );
  NAND _55_ (
    .A(_16_),
    .B(reset_L),
    .Y(_17_)
  );
  NOR _56_ (
    .A(_17_),
    .B(_14_),
    .Y(data_demux_0[3])
  );
  NOR _57_ (
    .A(data_reg0[4]),
    .B(valid_unstripped),
    .Y(_18_)
  );
  NOT _58_ (
    .A(data_unstripped[4]),
    .Y(_19_)
  );
  NAND _59_ (
    .A(_19_),
    .B(valid_unstripped),
    .Y(_20_)
  );
  NAND _60_ (
    .A(_20_),
    .B(reset_L),
    .Y(_21_)
  );
  NOR _61_ (
    .A(_21_),
    .B(_18_),
    .Y(data_demux_0[4])
  );
  NOR _62_ (
    .A(data_reg0[5]),
    .B(valid_unstripped),
    .Y(_22_)
  );
  NOT _63_ (
    .A(data_unstripped[5]),
    .Y(_23_)
  );
  NAND _64_ (
    .A(_23_),
    .B(valid_unstripped),
    .Y(_24_)
  );
  NAND _65_ (
    .A(_24_),
    .B(reset_L),
    .Y(_25_)
  );
  NOR _66_ (
    .A(_25_),
    .B(_22_),
    .Y(data_demux_0[5])
  );
  NOR _67_ (
    .A(data_reg0[6]),
    .B(valid_unstripped),
    .Y(_26_)
  );
  NOT _68_ (
    .A(data_unstripped[6]),
    .Y(_27_)
  );
  NAND _69_ (
    .A(_27_),
    .B(valid_unstripped),
    .Y(_28_)
  );
  NAND _70_ (
    .A(_28_),
    .B(reset_L),
    .Y(_29_)
  );
  NOR _71_ (
    .A(_29_),
    .B(_26_),
    .Y(data_demux_0[6])
  );
  NOR _72_ (
    .A(data_reg0[7]),
    .B(valid_unstripped),
    .Y(_30_)
  );
  NOT _73_ (
    .A(data_unstripped[7]),
    .Y(_31_)
  );
  NAND _74_ (
    .A(_31_),
    .B(valid_unstripped),
    .Y(_32_)
  );
  NAND _75_ (
    .A(_32_),
    .B(reset_L),
    .Y(_33_)
  );
  NOR _76_ (
    .A(_33_),
    .B(_30_),
    .Y(data_demux_0[7])
  );
  DFF _77_ (
    .C(clk_2f),
    .D(data_demux_0[0]),
    .Q(data_reg0[0])
  );
  DFF _78_ (
    .C(clk_2f),
    .D(data_demux_0[1]),
    .Q(data_reg0[1])
  );
  DFF _79_ (
    .C(clk_2f),
    .D(data_demux_0[2]),
    .Q(data_reg0[2])
  );
  DFF _80_ (
    .C(clk_2f),
    .D(data_demux_0[3]),
    .Q(data_reg0[3])
  );
  DFF _81_ (
    .C(clk_2f),
    .D(data_demux_0[4]),
    .Q(data_reg0[4])
  );
  DFF _82_ (
    .C(clk_2f),
    .D(data_demux_0[5]),
    .Q(data_reg0[5])
  );
  DFF _83_ (
    .C(clk_2f),
    .D(data_demux_0[6]),
    .Q(data_reg0[6])
  );
  DFF _84_ (
    .C(clk_2f),
    .D(data_demux_0[7]),
    .Q(data_reg0[7])
  );
  assign data_demux_1 = 8'b00000000;
  assign valid_demux_1 = 1'b0;
endmodule

module gen_clk(clk_8f, enable, clk_2f, clk_f);
  wire _00_;
  wire _01_;
  wire [1:0] _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  output clk_2f;
  input clk_8f;
  output clk_f;
  wire [1:0] counter;
  input enable;
  NOT _17_ (
    .A(enable),
    .Y(_03_)
  );
  NOT _18_ (
    .A(counter[0]),
    .Y(_04_)
  );
  NOT _19_ (
    .A(counter[1]),
    .Y(_05_)
  );
  NAND _20_ (
    .A(_05_),
    .B(_04_),
    .Y(_06_)
  );
  NOR _21_ (
    .A(_06_),
    .B(_03_),
    .Y(_02_[0])
  );
  NOT _22_ (
    .A(clk_f),
    .Y(_07_)
  );
  NOR _23_ (
    .A(counter[1]),
    .B(counter[0]),
    .Y(_08_)
  );
  NOR _24_ (
    .A(_08_),
    .B(clk_2f),
    .Y(_09_)
  );
  NOR _25_ (
    .A(_09_),
    .B(_07_),
    .Y(_10_)
  );
  NOT _26_ (
    .A(clk_2f),
    .Y(_11_)
  );
  NAND _27_ (
    .A(_06_),
    .B(_11_),
    .Y(_12_)
  );
  NOR _28_ (
    .A(_12_),
    .B(clk_f),
    .Y(_13_)
  );
  NOR _29_ (
    .A(_13_),
    .B(_10_),
    .Y(_14_)
  );
  NOR _30_ (
    .A(_14_),
    .B(_03_),
    .Y(_01_)
  );
  NOR _31_ (
    .A(_06_),
    .B(_11_),
    .Y(_15_)
  );
  NOR _32_ (
    .A(_15_),
    .B(_09_),
    .Y(_16_)
  );
  NOR _33_ (
    .A(_16_),
    .B(_03_),
    .Y(_00_)
  );
  DFF _34_ (
    .C(clk_8f),
    .D(_00_),
    .Q(clk_2f)
  );
  DFF _35_ (
    .C(clk_8f),
    .D(_01_),
    .Q(clk_f)
  );
  DFF _36_ (
    .C(clk_8f),
    .D(_02_[0]),
    .Q(counter[0])
  );
  DFF _37_ (
    .C(clk_8f),
    .D(1'b0),
    .Q(counter[1])
  );
endmodule

module phy_rxSynth(clk_8f, reset_L, in_0, in_1, enable, data_out_0_estruct, data_out_1_estruct, valid_out_0_estruct, valid_out_1_estruct);
  wire [7:0] _00_;
  wire [7:0] _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire clk_2f;
  input clk_8f;
  wire clk_f;
  wire [7:0] data_demux_0;
  wire [7:0] data_demux_1;
  output [7:0] data_out_0_estruct;
  output [7:0] data_out_1_estruct;
  wire [7:0] data_par_0;
  wire [7:0] data_par_1;
  wire [7:0] data_unstripped;
  input enable;
  input in_0;
  input in_1;
  input reset_L;
  wire valid_demux_0;
  wire valid_demux_1;
  output valid_out_0_estruct;
  output valid_out_1_estruct;
  wire valid_par_0;
  wire valid_par_1;
  wire valid_unstripped;
  NOT _23_ (
    .A(valid_demux_0),
    .Y(_04_)
  );
  NOT _24_ (
    .A(reset_L),
    .Y(_05_)
  );
  NOR _25_ (
    .A(_05_),
    .B(_04_),
    .Y(_02_)
  );
  NOT _26_ (
    .A(data_demux_1[0]),
    .Y(_06_)
  );
  NOR _27_ (
    .A(_06_),
    .B(_05_),
    .Y(_01_[0])
  );
  NOT _28_ (
    .A(data_demux_1[1]),
    .Y(_07_)
  );
  NOR _29_ (
    .A(_07_),
    .B(_05_),
    .Y(_01_[1])
  );
  NOT _30_ (
    .A(data_demux_1[2]),
    .Y(_08_)
  );
  NOR _31_ (
    .A(_08_),
    .B(_05_),
    .Y(_01_[2])
  );
  NOT _32_ (
    .A(data_demux_1[3]),
    .Y(_09_)
  );
  NOR _33_ (
    .A(_09_),
    .B(_05_),
    .Y(_01_[3])
  );
  NOT _34_ (
    .A(data_demux_1[4]),
    .Y(_10_)
  );
  NOR _35_ (
    .A(_10_),
    .B(_05_),
    .Y(_01_[4])
  );
  NOT _36_ (
    .A(data_demux_1[5]),
    .Y(_11_)
  );
  NOR _37_ (
    .A(_11_),
    .B(_05_),
    .Y(_01_[5])
  );
  NOT _38_ (
    .A(data_demux_1[6]),
    .Y(_12_)
  );
  NOR _39_ (
    .A(_12_),
    .B(_05_),
    .Y(_01_[6])
  );
  NOT _40_ (
    .A(data_demux_1[7]),
    .Y(_13_)
  );
  NOR _41_ (
    .A(_13_),
    .B(_05_),
    .Y(_01_[7])
  );
  NOT _42_ (
    .A(data_demux_0[0]),
    .Y(_14_)
  );
  NOR _43_ (
    .A(_14_),
    .B(_05_),
    .Y(_00_[0])
  );
  NOT _44_ (
    .A(data_demux_0[1]),
    .Y(_15_)
  );
  NOR _45_ (
    .A(_15_),
    .B(_05_),
    .Y(_00_[1])
  );
  NOT _46_ (
    .A(data_demux_0[2]),
    .Y(_16_)
  );
  NOR _47_ (
    .A(_16_),
    .B(_05_),
    .Y(_00_[2])
  );
  NOT _48_ (
    .A(data_demux_0[3]),
    .Y(_17_)
  );
  NOR _49_ (
    .A(_17_),
    .B(_05_),
    .Y(_00_[3])
  );
  NOT _50_ (
    .A(data_demux_0[4]),
    .Y(_18_)
  );
  NOR _51_ (
    .A(_18_),
    .B(_05_),
    .Y(_00_[4])
  );
  NOT _52_ (
    .A(data_demux_0[5]),
    .Y(_19_)
  );
  NOR _53_ (
    .A(_19_),
    .B(_05_),
    .Y(_00_[5])
  );
  NOT _54_ (
    .A(data_demux_0[6]),
    .Y(_20_)
  );
  NOR _55_ (
    .A(_20_),
    .B(_05_),
    .Y(_00_[6])
  );
  NOT _56_ (
    .A(data_demux_0[7]),
    .Y(_21_)
  );
  NOR _57_ (
    .A(_21_),
    .B(_05_),
    .Y(_00_[7])
  );
  NOT _58_ (
    .A(valid_demux_1),
    .Y(_22_)
  );
  NOR _59_ (
    .A(_22_),
    .B(_05_),
    .Y(_03_)
  );
  DFF _60_ (
    .C(clk_2f),
    .D(_00_[0]),
    .Q(data_out_0_estruct[0])
  );
  DFF _61_ (
    .C(clk_2f),
    .D(_00_[1]),
    .Q(data_out_0_estruct[1])
  );
  DFF _62_ (
    .C(clk_2f),
    .D(_00_[2]),
    .Q(data_out_0_estruct[2])
  );
  DFF _63_ (
    .C(clk_2f),
    .D(_00_[3]),
    .Q(data_out_0_estruct[3])
  );
  DFF _64_ (
    .C(clk_2f),
    .D(_00_[4]),
    .Q(data_out_0_estruct[4])
  );
  DFF _65_ (
    .C(clk_2f),
    .D(_00_[5]),
    .Q(data_out_0_estruct[5])
  );
  DFF _66_ (
    .C(clk_2f),
    .D(_00_[6]),
    .Q(data_out_0_estruct[6])
  );
  DFF _67_ (
    .C(clk_2f),
    .D(_00_[7]),
    .Q(data_out_0_estruct[7])
  );
  DFF _68_ (
    .C(clk_2f),
    .D(_01_[0]),
    .Q(data_out_1_estruct[0])
  );
  DFF _69_ (
    .C(clk_2f),
    .D(_01_[1]),
    .Q(data_out_1_estruct[1])
  );
  DFF _70_ (
    .C(clk_2f),
    .D(_01_[2]),
    .Q(data_out_1_estruct[2])
  );
  DFF _71_ (
    .C(clk_2f),
    .D(_01_[3]),
    .Q(data_out_1_estruct[3])
  );
  DFF _72_ (
    .C(clk_2f),
    .D(_01_[4]),
    .Q(data_out_1_estruct[4])
  );
  DFF _73_ (
    .C(clk_2f),
    .D(_01_[5]),
    .Q(data_out_1_estruct[5])
  );
  DFF _74_ (
    .C(clk_2f),
    .D(_01_[6]),
    .Q(data_out_1_estruct[6])
  );
  DFF _75_ (
    .C(clk_2f),
    .D(_01_[7]),
    .Q(data_out_1_estruct[7])
  );
  DFF _76_ (
    .C(clk_2f),
    .D(_02_),
    .Q(valid_out_0_estruct)
  );
  DFF _77_ (
    .C(clk_2f),
    .D(_03_),
    .Q(valid_out_1_estruct)
  );
  byte_unstripping byte_uns (
    .clk_2f(clk_2f),
    .data_par_0(data_par_0),
    .data_par_1(data_par_1),
    .data_unstripped(data_unstripped),
    .reset_L(reset_L),
    .valid_par_0(valid_par_0),
    .valid_par_1(valid_par_1),
    .valid_unstripped(valid_unstripped)
  );
  gen_clk clocks (
    .clk_2f(clk_2f),
    .clk_8f(clk_8f),
    .clk_f(clk_f),
    .enable(enable)
  );
  demux demux0 (
    .clk_2f(clk_2f),
    .data_demux_0(data_demux_0),
    .data_demux_1(data_demux_1),
    .data_unstripped(data_unstripped),
    .reset_L(reset_L),
    .valid_demux_0(valid_demux_0),
    .valid_demux_1(valid_demux_1),
    .valid_unstripped(valid_unstripped)
  );
  serialtopar line0 (
    .clk_8f(clk_8f),
    .clk_f(clk_f),
    .data_par(data_par_0),
    .in(in_0),
    .reset_L(reset_L),
    .valid_par(valid_par_0)
  );
  serialtopar line1 (
    .clk_8f(clk_8f),
    .clk_f(clk_f),
    .data_par(data_par_1),
    .in(in_1),
    .reset_L(reset_L),
    .valid_par(valid_par_1)
  );
endmodule

module serialtopar(data_par, valid_par, clk_f, clk_8f, reset_L, in);
  wire _000_;
  wire [2:0] _001_;
  wire [7:0] _002_;
  wire [7:0] _003_;
  wire [2:0] _004_;
  wire [7:0] _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire active;
  wire [2:0] bc_cnt;
  wire [7:0] buffer;
  wire [7:0] buffer2;
  input clk_8f;
  input clk_f;
  wire [2:0] cnt_bits;
  output [7:0] data_par;
  input in;
  input reset_L;
  wire [7:0] shift_reg;
  wire valid;
  output valid_par;
  NOT _082_ (
    .A(valid),
    .Y(_053_)
  );
  NOT _083_ (
    .A(reset_L),
    .Y(_054_)
  );
  NOR _084_ (
    .A(_054_),
    .B(_053_),
    .Y(_007_)
  );
  NOT _085_ (
    .A(buffer2[0]),
    .Y(_055_)
  );
  NOR _086_ (
    .A(_054_),
    .B(_055_),
    .Y(_005_[0])
  );
  NOT _087_ (
    .A(buffer2[1]),
    .Y(_056_)
  );
  NOR _088_ (
    .A(_054_),
    .B(_056_),
    .Y(_005_[1])
  );
  NOT _089_ (
    .A(buffer2[2]),
    .Y(_057_)
  );
  NOR _090_ (
    .A(_057_),
    .B(_054_),
    .Y(_005_[2])
  );
  NOT _091_ (
    .A(buffer2[3]),
    .Y(_058_)
  );
  NOR _092_ (
    .A(_058_),
    .B(_054_),
    .Y(_005_[3])
  );
  NOT _093_ (
    .A(buffer2[4]),
    .Y(_059_)
  );
  NOR _094_ (
    .A(_059_),
    .B(_054_),
    .Y(_005_[4])
  );
  NOT _095_ (
    .A(buffer2[5]),
    .Y(_060_)
  );
  NOR _096_ (
    .A(_060_),
    .B(_054_),
    .Y(_005_[5])
  );
  NOT _097_ (
    .A(buffer2[6]),
    .Y(_061_)
  );
  NOR _098_ (
    .A(_054_),
    .B(_061_),
    .Y(_005_[6])
  );
  NOT _099_ (
    .A(buffer2[7]),
    .Y(_062_)
  );
  NOR _100_ (
    .A(_062_),
    .B(_054_),
    .Y(_005_[7])
  );
  NOR _101_ (
    .A(active),
    .B(bc_cnt[2]),
    .Y(_063_)
  );
  NOR _102_ (
    .A(_063_),
    .B(_054_),
    .Y(_000_)
  );
  NOR _103_ (
    .A(_054_),
    .B(cnt_bits[0]),
    .Y(_004_[0])
  );
  NAND _104_ (
    .A(cnt_bits[1]),
    .B(cnt_bits[0]),
    .Y(_064_)
  );
  NOT _105_ (
    .A(_064_),
    .Y(_065_)
  );
  NOR _106_ (
    .A(cnt_bits[1]),
    .B(cnt_bits[0]),
    .Y(_066_)
  );
  NOT _107_ (
    .A(_066_),
    .Y(_067_)
  );
  NAND _108_ (
    .A(_067_),
    .B(reset_L),
    .Y(_068_)
  );
  NOR _109_ (
    .A(_068_),
    .B(_065_),
    .Y(_004_[1])
  );
  NOT _110_ (
    .A(cnt_bits[2]),
    .Y(_069_)
  );
  NOR _111_ (
    .A(_064_),
    .B(_069_),
    .Y(_070_)
  );
  NAND _112_ (
    .A(_064_),
    .B(_069_),
    .Y(_071_)
  );
  NAND _113_ (
    .A(_071_),
    .B(reset_L),
    .Y(_072_)
  );
  NOR _114_ (
    .A(_072_),
    .B(_070_),
    .Y(_004_[2])
  );
  NOT _115_ (
    .A(bc_cnt[0]),
    .Y(_073_)
  );
  NOT _116_ (
    .A(buffer[2]),
    .Y(_074_)
  );
  NOT _117_ (
    .A(buffer[3]),
    .Y(_075_)
  );
  NOR _118_ (
    .A(_075_),
    .B(_074_),
    .Y(_076_)
  );
  NOT _119_ (
    .A(buffer[4]),
    .Y(_077_)
  );
  NOT _120_ (
    .A(buffer[6]),
    .Y(_078_)
  );
  NOR _121_ (
    .A(_078_),
    .B(_077_),
    .Y(_079_)
  );
  NAND _122_ (
    .A(_079_),
    .B(_076_),
    .Y(_080_)
  );
  NOR _123_ (
    .A(buffer[0]),
    .B(in),
    .Y(_081_)
  );
  NOT _124_ (
    .A(buffer[1]),
    .Y(_008_)
  );
  NOR _125_ (
    .A(_008_),
    .B(buffer[5]),
    .Y(_009_)
  );
  NAND _126_ (
    .A(_009_),
    .B(_081_),
    .Y(_010_)
  );
  NOR _127_ (
    .A(_010_),
    .B(_080_),
    .Y(_011_)
  );
  NOT _128_ (
    .A(_011_),
    .Y(_012_)
  );
  NAND _129_ (
    .A(_012_),
    .B(_073_),
    .Y(_013_)
  );
  NAND _130_ (
    .A(_013_),
    .B(reset_L),
    .Y(_014_)
  );
  NAND _131_ (
    .A(_011_),
    .B(bc_cnt[0]),
    .Y(_015_)
  );
  NOT _132_ (
    .A(_015_),
    .Y(_016_)
  );
  NOR _133_ (
    .A(_016_),
    .B(_014_),
    .Y(_001_[0])
  );
  NOT _134_ (
    .A(bc_cnt[1]),
    .Y(_017_)
  );
  NAND _135_ (
    .A(_015_),
    .B(_017_),
    .Y(_018_)
  );
  NAND _136_ (
    .A(_018_),
    .B(reset_L),
    .Y(_019_)
  );
  NOR _137_ (
    .A(_015_),
    .B(_017_),
    .Y(_020_)
  );
  NOR _138_ (
    .A(_020_),
    .B(_019_),
    .Y(_001_[1])
  );
  NOR _139_ (
    .A(_020_),
    .B(bc_cnt[2]),
    .Y(_021_)
  );
  NAND _140_ (
    .A(_020_),
    .B(bc_cnt[2]),
    .Y(_022_)
  );
  NAND _141_ (
    .A(_022_),
    .B(reset_L),
    .Y(_023_)
  );
  NOR _142_ (
    .A(_023_),
    .B(_021_),
    .Y(_001_[2])
  );
  NAND _143_ (
    .A(_066_),
    .B(_069_),
    .Y(_024_)
  );
  NOR _144_ (
    .A(_024_),
    .B(in),
    .Y(_025_)
  );
  NOR _145_ (
    .A(_024_),
    .B(_054_),
    .Y(_026_)
  );
  NOR _146_ (
    .A(_026_),
    .B(_005_[0]),
    .Y(_027_)
  );
  NOR _147_ (
    .A(_027_),
    .B(_025_),
    .Y(_002_[0])
  );
  NOR _148_ (
    .A(_024_),
    .B(buffer[0]),
    .Y(_028_)
  );
  NOR _149_ (
    .A(_026_),
    .B(_005_[1]),
    .Y(_029_)
  );
  NOR _150_ (
    .A(_029_),
    .B(_028_),
    .Y(_002_[1])
  );
  NOR _151_ (
    .A(_024_),
    .B(buffer[1]),
    .Y(_030_)
  );
  NOR _152_ (
    .A(_026_),
    .B(_005_[2]),
    .Y(_031_)
  );
  NOR _153_ (
    .A(_031_),
    .B(_030_),
    .Y(_002_[2])
  );
  NOR _154_ (
    .A(_024_),
    .B(buffer[2]),
    .Y(_032_)
  );
  NOR _155_ (
    .A(_026_),
    .B(_005_[3]),
    .Y(_033_)
  );
  NOR _156_ (
    .A(_033_),
    .B(_032_),
    .Y(_002_[3])
  );
  NOR _157_ (
    .A(_024_),
    .B(buffer[3]),
    .Y(_034_)
  );
  NOR _158_ (
    .A(_026_),
    .B(_005_[4]),
    .Y(_035_)
  );
  NOR _159_ (
    .A(_035_),
    .B(_034_),
    .Y(_002_[4])
  );
  NOR _160_ (
    .A(_024_),
    .B(buffer[4]),
    .Y(_036_)
  );
  NOR _161_ (
    .A(_026_),
    .B(_005_[5]),
    .Y(_037_)
  );
  NOR _162_ (
    .A(_037_),
    .B(_036_),
    .Y(_002_[5])
  );
  NOR _163_ (
    .A(_024_),
    .B(buffer[5]),
    .Y(_038_)
  );
  NOR _164_ (
    .A(_026_),
    .B(_005_[6]),
    .Y(_039_)
  );
  NOR _165_ (
    .A(_039_),
    .B(_038_),
    .Y(_002_[6])
  );
  NOR _166_ (
    .A(_024_),
    .B(buffer[6]),
    .Y(_040_)
  );
  NOR _167_ (
    .A(_026_),
    .B(_005_[7]),
    .Y(_041_)
  );
  NOR _168_ (
    .A(_041_),
    .B(_040_),
    .Y(_002_[7])
  );
  NOT _169_ (
    .A(in),
    .Y(_042_)
  );
  NOR _170_ (
    .A(_042_),
    .B(_054_),
    .Y(_003_[0])
  );
  NOT _171_ (
    .A(buffer[0]),
    .Y(_043_)
  );
  NOR _172_ (
    .A(_043_),
    .B(_054_),
    .Y(_003_[1])
  );
  NOR _173_ (
    .A(_008_),
    .B(_054_),
    .Y(_003_[2])
  );
  NOR _174_ (
    .A(_074_),
    .B(_054_),
    .Y(_003_[3])
  );
  NOR _175_ (
    .A(_075_),
    .B(_054_),
    .Y(_003_[4])
  );
  NOR _176_ (
    .A(_077_),
    .B(_054_),
    .Y(_003_[5])
  );
  NOT _177_ (
    .A(buffer[5]),
    .Y(_044_)
  );
  NOR _178_ (
    .A(_054_),
    .B(_044_),
    .Y(_003_[6])
  );
  NOT _179_ (
    .A(_000_),
    .Y(_045_)
  );
  NOR _180_ (
    .A(_059_),
    .B(_058_),
    .Y(_046_)
  );
  NOR _181_ (
    .A(_062_),
    .B(_060_),
    .Y(_047_)
  );
  NAND _182_ (
    .A(_047_),
    .B(_046_),
    .Y(_048_)
  );
  NOR _183_ (
    .A(buffer2[1]),
    .B(buffer2[0]),
    .Y(_049_)
  );
  NOR _184_ (
    .A(_057_),
    .B(buffer2[6]),
    .Y(_050_)
  );
  NAND _185_ (
    .A(_050_),
    .B(_049_),
    .Y(_051_)
  );
  NOR _186_ (
    .A(_051_),
    .B(_048_),
    .Y(_052_)
  );
  NOR _187_ (
    .A(_052_),
    .B(_045_),
    .Y(_006_)
  );
  DFF _188_ (
    .C(clk_f),
    .D(_005_[0]),
    .Q(data_par[0])
  );
  DFF _189_ (
    .C(clk_f),
    .D(_005_[1]),
    .Q(data_par[1])
  );
  DFF _190_ (
    .C(clk_f),
    .D(_005_[2]),
    .Q(data_par[2])
  );
  DFF _191_ (
    .C(clk_f),
    .D(_005_[3]),
    .Q(data_par[3])
  );
  DFF _192_ (
    .C(clk_f),
    .D(_005_[4]),
    .Q(data_par[4])
  );
  DFF _193_ (
    .C(clk_f),
    .D(_005_[5]),
    .Q(data_par[5])
  );
  DFF _194_ (
    .C(clk_f),
    .D(_005_[6]),
    .Q(data_par[6])
  );
  DFF _195_ (
    .C(clk_f),
    .D(_005_[7]),
    .Q(data_par[7])
  );
  DFF _196_ (
    .C(clk_f),
    .D(_007_),
    .Q(valid_par)
  );
  DFF _197_ (
    .C(clk_8f),
    .D(_000_),
    .Q(active)
  );
  DFF _198_ (
    .C(clk_8f),
    .D(_006_),
    .Q(valid)
  );
  DFF _199_ (
    .C(clk_8f),
    .D(_003_[0]),
    .Q(buffer[0])
  );
  DFF _200_ (
    .C(clk_8f),
    .D(_003_[1]),
    .Q(buffer[1])
  );
  DFF _201_ (
    .C(clk_8f),
    .D(_003_[2]),
    .Q(buffer[2])
  );
  DFF _202_ (
    .C(clk_8f),
    .D(_003_[3]),
    .Q(buffer[3])
  );
  DFF _203_ (
    .C(clk_8f),
    .D(_003_[4]),
    .Q(buffer[4])
  );
  DFF _204_ (
    .C(clk_8f),
    .D(_003_[5]),
    .Q(buffer[5])
  );
  DFF _205_ (
    .C(clk_8f),
    .D(_003_[6]),
    .Q(buffer[6])
  );
  DFF _206_ (
    .C(clk_8f),
    .D(_002_[0]),
    .Q(buffer2[0])
  );
  DFF _207_ (
    .C(clk_8f),
    .D(_002_[1]),
    .Q(buffer2[1])
  );
  DFF _208_ (
    .C(clk_8f),
    .D(_002_[2]),
    .Q(buffer2[2])
  );
  DFF _209_ (
    .C(clk_8f),
    .D(_002_[3]),
    .Q(buffer2[3])
  );
  DFF _210_ (
    .C(clk_8f),
    .D(_002_[4]),
    .Q(buffer2[4])
  );
  DFF _211_ (
    .C(clk_8f),
    .D(_002_[5]),
    .Q(buffer2[5])
  );
  DFF _212_ (
    .C(clk_8f),
    .D(_002_[6]),
    .Q(buffer2[6])
  );
  DFF _213_ (
    .C(clk_8f),
    .D(_002_[7]),
    .Q(buffer2[7])
  );
  DFF _214_ (
    .C(clk_8f),
    .D(_001_[0]),
    .Q(bc_cnt[0])
  );
  DFF _215_ (
    .C(clk_8f),
    .D(_001_[1]),
    .Q(bc_cnt[1])
  );
  DFF _216_ (
    .C(clk_8f),
    .D(_001_[2]),
    .Q(bc_cnt[2])
  );
  DFF _217_ (
    .C(clk_8f),
    .D(_004_[0]),
    .Q(cnt_bits[0])
  );
  DFF _218_ (
    .C(clk_8f),
    .D(_004_[1]),
    .Q(cnt_bits[1])
  );
  DFF _219_ (
    .C(clk_8f),
    .D(_004_[2]),
    .Q(cnt_bits[2])
  );
  assign shift_reg = { buffer[6:0], in };
endmodule
