/* Generated by Yosys 0.8 (git sha1 UNKNOWN, clang 6.0.0-1ubuntu2 -fPIC -Os) */
`include "./CMOS/cmos_cells.v"

module byte_unstripping(data_unstripped, valid_unstripped, clk_2f, reset_L, data_par_0, data_par_1, valid_par_0, valid_par_1);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  input clk_2f;
  input [7:0] data_par_0;
  input [7:0] data_par_1;
  output [7:0] data_unstripped;
  wire lectura;
  input reset_L;
  wire selector;
  input valid_par_0;
  input valid_par_1;
  output valid_unstripped;
  NOT _43_ (
    .A(lectura),
    .Y(_02_)
  );
  NOT _44_ (
    .A(reset_L),
    .Y(_03_)
  );
  NOT _45_ (
    .A(valid_par_1),
    .Y(_04_)
  );
  NOT _46_ (
    .A(data_par_1[0]),
    .Y(_05_)
  );
  NOT _47_ (
    .A(data_par_1[1]),
    .Y(_06_)
  );
  NOT _48_ (
    .A(data_par_1[2]),
    .Y(_07_)
  );
  NOT _49_ (
    .A(data_par_1[3]),
    .Y(_08_)
  );
  NOT _50_ (
    .A(data_par_1[4]),
    .Y(_09_)
  );
  NOT _51_ (
    .A(data_par_1[5]),
    .Y(_10_)
  );
  NOT _52_ (
    .A(data_par_1[6]),
    .Y(_11_)
  );
  NOT _53_ (
    .A(data_par_1[7]),
    .Y(_12_)
  );
  NOR _54_ (
    .A(_02_),
    .B(_03_),
    .Y(_13_)
  );
  NAND _55_ (
    .A(lectura),
    .B(reset_L),
    .Y(_14_)
  );
  NOR _56_ (
    .A(selector),
    .B(_14_),
    .Y(_01_)
  );
  NOR _57_ (
    .A(valid_par_0),
    .B(selector),
    .Y(_15_)
  );
  NAND _58_ (
    .A(_04_),
    .B(selector),
    .Y(_16_)
  );
  NAND _59_ (
    .A(_13_),
    .B(_16_),
    .Y(_17_)
  );
  NOR _60_ (
    .A(_15_),
    .B(_17_),
    .Y(valid_unstripped)
  );
  NOR _61_ (
    .A(selector),
    .B(data_par_0[0]),
    .Y(_18_)
  );
  NAND _62_ (
    .A(selector),
    .B(_05_),
    .Y(_19_)
  );
  NAND _63_ (
    .A(_13_),
    .B(_19_),
    .Y(_20_)
  );
  NOR _64_ (
    .A(_18_),
    .B(_20_),
    .Y(data_unstripped[0])
  );
  NOR _65_ (
    .A(selector),
    .B(data_par_0[1]),
    .Y(_21_)
  );
  NAND _66_ (
    .A(selector),
    .B(_06_),
    .Y(_22_)
  );
  NAND _67_ (
    .A(_13_),
    .B(_22_),
    .Y(_23_)
  );
  NOR _68_ (
    .A(_21_),
    .B(_23_),
    .Y(data_unstripped[1])
  );
  NOR _69_ (
    .A(selector),
    .B(data_par_0[2]),
    .Y(_24_)
  );
  NAND _70_ (
    .A(selector),
    .B(_07_),
    .Y(_25_)
  );
  NAND _71_ (
    .A(_13_),
    .B(_25_),
    .Y(_26_)
  );
  NOR _72_ (
    .A(_24_),
    .B(_26_),
    .Y(data_unstripped[2])
  );
  NOR _73_ (
    .A(selector),
    .B(data_par_0[3]),
    .Y(_27_)
  );
  NAND _74_ (
    .A(selector),
    .B(_08_),
    .Y(_28_)
  );
  NAND _75_ (
    .A(_13_),
    .B(_28_),
    .Y(_29_)
  );
  NOR _76_ (
    .A(_27_),
    .B(_29_),
    .Y(data_unstripped[3])
  );
  NOR _77_ (
    .A(selector),
    .B(data_par_0[4]),
    .Y(_30_)
  );
  NAND _78_ (
    .A(selector),
    .B(_09_),
    .Y(_31_)
  );
  NAND _79_ (
    .A(_13_),
    .B(_31_),
    .Y(_32_)
  );
  NOR _80_ (
    .A(_30_),
    .B(_32_),
    .Y(data_unstripped[4])
  );
  NOR _81_ (
    .A(selector),
    .B(data_par_0[5]),
    .Y(_33_)
  );
  NAND _82_ (
    .A(selector),
    .B(_10_),
    .Y(_34_)
  );
  NAND _83_ (
    .A(_13_),
    .B(_34_),
    .Y(_35_)
  );
  NOR _84_ (
    .A(_33_),
    .B(_35_),
    .Y(data_unstripped[5])
  );
  NOR _85_ (
    .A(selector),
    .B(data_par_0[6]),
    .Y(_36_)
  );
  NAND _86_ (
    .A(selector),
    .B(_11_),
    .Y(_37_)
  );
  NAND _87_ (
    .A(_13_),
    .B(_37_),
    .Y(_38_)
  );
  NOR _88_ (
    .A(_36_),
    .B(_38_),
    .Y(data_unstripped[6])
  );
  NOR _89_ (
    .A(selector),
    .B(data_par_0[7]),
    .Y(_39_)
  );
  NAND _90_ (
    .A(selector),
    .B(_12_),
    .Y(_40_)
  );
  NAND _91_ (
    .A(_13_),
    .B(_40_),
    .Y(_41_)
  );
  NOR _92_ (
    .A(_39_),
    .B(_41_),
    .Y(data_unstripped[7])
  );
  NAND _93_ (
    .A(reset_L),
    .B(valid_par_0),
    .Y(_42_)
  );
  NOT _94_ (
    .A(_42_),
    .Y(_00_)
  );
  DFF _95_ (
    .C(clk_2f),
    .D(_01_),
    .Q(selector)
  );
  DFF _96_ (
    .C(clk_2f),
    .D(_00_),
    .Q(lectura)
  );
endmodule

module demux(data_demux_0, data_demux_1, valid_demux_0, valid_demux_1, valid_unstripped, clk_2f, reset_L, data_unstripped);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  input clk_2f;
  output [7:0] data_demux_0;
  output [7:0] data_demux_1;
  wire [7:0] data_reg0;
  wire [7:0] data_reg1;
  input [7:0] data_unstripped;
  input reset_L;
  wire selector;
  output valid_demux_0;
  output valid_demux_1;
  input valid_unstripped;
  NOT _066_ (
    .A(reset_L),
    .Y(_024_)
  );
  NOT _067_ (
    .A(data_unstripped[0]),
    .Y(_025_)
  );
  NOT _068_ (
    .A(data_unstripped[1]),
    .Y(_026_)
  );
  NOT _069_ (
    .A(data_unstripped[2]),
    .Y(_027_)
  );
  NOT _070_ (
    .A(data_unstripped[3]),
    .Y(_028_)
  );
  NOT _071_ (
    .A(data_unstripped[4]),
    .Y(_029_)
  );
  NOT _072_ (
    .A(data_unstripped[5]),
    .Y(_030_)
  );
  NOT _073_ (
    .A(data_unstripped[6]),
    .Y(_031_)
  );
  NOT _074_ (
    .A(data_unstripped[7]),
    .Y(_032_)
  );
  NOT _075_ (
    .A(selector),
    .Y(_033_)
  );
  NOT _076_ (
    .A(valid_unstripped),
    .Y(_034_)
  );
  NOR _077_ (
    .A(selector),
    .B(_034_),
    .Y(_035_)
  );
  NAND _078_ (
    .A(selector),
    .B(_034_),
    .Y(_036_)
  );
  NAND _079_ (
    .A(reset_L),
    .B(_036_),
    .Y(_037_)
  );
  NOR _080_ (
    .A(_035_),
    .B(_037_),
    .Y(_000_)
  );
  NOR _081_ (
    .A(_033_),
    .B(_034_),
    .Y(_038_)
  );
  NAND _082_ (
    .A(selector),
    .B(valid_unstripped),
    .Y(_039_)
  );
  NOR _083_ (
    .A(_024_),
    .B(_039_),
    .Y(valid_demux_1)
  );
  NAND _084_ (
    .A(reset_L),
    .B(_035_),
    .Y(_040_)
  );
  NOT _085_ (
    .A(_040_),
    .Y(valid_demux_0)
  );
  NAND _086_ (
    .A(_025_),
    .B(_038_),
    .Y(_041_)
  );
  NAND _087_ (
    .A(reset_L),
    .B(_041_),
    .Y(_042_)
  );
  NOR _088_ (
    .A(data_reg1[0]),
    .B(_038_),
    .Y(_043_)
  );
  NOR _089_ (
    .A(_042_),
    .B(_043_),
    .Y(data_demux_1[0])
  );
  NAND _090_ (
    .A(_026_),
    .B(_038_),
    .Y(_044_)
  );
  NAND _091_ (
    .A(reset_L),
    .B(_044_),
    .Y(_045_)
  );
  NOR _092_ (
    .A(data_reg1[1]),
    .B(_038_),
    .Y(_046_)
  );
  NOR _093_ (
    .A(_045_),
    .B(_046_),
    .Y(data_demux_1[1])
  );
  NAND _094_ (
    .A(_027_),
    .B(_038_),
    .Y(_047_)
  );
  NAND _095_ (
    .A(reset_L),
    .B(_047_),
    .Y(_048_)
  );
  NOR _096_ (
    .A(data_reg1[2]),
    .B(_038_),
    .Y(_049_)
  );
  NOR _097_ (
    .A(_048_),
    .B(_049_),
    .Y(data_demux_1[2])
  );
  NAND _098_ (
    .A(_028_),
    .B(_038_),
    .Y(_050_)
  );
  NAND _099_ (
    .A(reset_L),
    .B(_050_),
    .Y(_051_)
  );
  NOR _100_ (
    .A(data_reg1[3]),
    .B(_038_),
    .Y(_052_)
  );
  NOR _101_ (
    .A(_051_),
    .B(_052_),
    .Y(data_demux_1[3])
  );
  NAND _102_ (
    .A(_029_),
    .B(_038_),
    .Y(_053_)
  );
  NAND _103_ (
    .A(reset_L),
    .B(_053_),
    .Y(_054_)
  );
  NOR _104_ (
    .A(data_reg1[4]),
    .B(_038_),
    .Y(_055_)
  );
  NOR _105_ (
    .A(_054_),
    .B(_055_),
    .Y(data_demux_1[4])
  );
  NAND _106_ (
    .A(_030_),
    .B(_038_),
    .Y(_056_)
  );
  NAND _107_ (
    .A(reset_L),
    .B(_056_),
    .Y(_057_)
  );
  NOR _108_ (
    .A(data_reg1[5]),
    .B(_038_),
    .Y(_058_)
  );
  NOR _109_ (
    .A(_057_),
    .B(_058_),
    .Y(data_demux_1[5])
  );
  NAND _110_ (
    .A(_031_),
    .B(_038_),
    .Y(_059_)
  );
  NAND _111_ (
    .A(reset_L),
    .B(_059_),
    .Y(_060_)
  );
  NOR _112_ (
    .A(data_reg1[6]),
    .B(_038_),
    .Y(_061_)
  );
  NOR _113_ (
    .A(_060_),
    .B(_061_),
    .Y(data_demux_1[6])
  );
  NAND _114_ (
    .A(_032_),
    .B(_038_),
    .Y(_062_)
  );
  NAND _115_ (
    .A(reset_L),
    .B(_062_),
    .Y(_063_)
  );
  NOR _116_ (
    .A(data_reg1[7]),
    .B(_038_),
    .Y(_064_)
  );
  NOR _117_ (
    .A(_063_),
    .B(_064_),
    .Y(data_demux_1[7])
  );
  NAND _118_ (
    .A(_025_),
    .B(_035_),
    .Y(_065_)
  );
  NAND _119_ (
    .A(reset_L),
    .B(_065_),
    .Y(_001_)
  );
  NOR _120_ (
    .A(data_reg0[0]),
    .B(_035_),
    .Y(_002_)
  );
  NOR _121_ (
    .A(_001_),
    .B(_002_),
    .Y(data_demux_0[0])
  );
  NAND _122_ (
    .A(_026_),
    .B(_035_),
    .Y(_003_)
  );
  NAND _123_ (
    .A(reset_L),
    .B(_003_),
    .Y(_004_)
  );
  NOR _124_ (
    .A(data_reg0[1]),
    .B(_035_),
    .Y(_005_)
  );
  NOR _125_ (
    .A(_004_),
    .B(_005_),
    .Y(data_demux_0[1])
  );
  NAND _126_ (
    .A(_027_),
    .B(_035_),
    .Y(_006_)
  );
  NAND _127_ (
    .A(reset_L),
    .B(_006_),
    .Y(_007_)
  );
  NOR _128_ (
    .A(data_reg0[2]),
    .B(_035_),
    .Y(_008_)
  );
  NOR _129_ (
    .A(_007_),
    .B(_008_),
    .Y(data_demux_0[2])
  );
  NAND _130_ (
    .A(_028_),
    .B(_035_),
    .Y(_009_)
  );
  NAND _131_ (
    .A(reset_L),
    .B(_009_),
    .Y(_010_)
  );
  NOR _132_ (
    .A(data_reg0[3]),
    .B(_035_),
    .Y(_011_)
  );
  NOR _133_ (
    .A(_010_),
    .B(_011_),
    .Y(data_demux_0[3])
  );
  NAND _134_ (
    .A(_029_),
    .B(_035_),
    .Y(_012_)
  );
  NAND _135_ (
    .A(reset_L),
    .B(_012_),
    .Y(_013_)
  );
  NOR _136_ (
    .A(data_reg0[4]),
    .B(_035_),
    .Y(_014_)
  );
  NOR _137_ (
    .A(_013_),
    .B(_014_),
    .Y(data_demux_0[4])
  );
  NAND _138_ (
    .A(_030_),
    .B(_035_),
    .Y(_015_)
  );
  NAND _139_ (
    .A(reset_L),
    .B(_015_),
    .Y(_016_)
  );
  NOR _140_ (
    .A(data_reg0[5]),
    .B(_035_),
    .Y(_017_)
  );
  NOR _141_ (
    .A(_016_),
    .B(_017_),
    .Y(data_demux_0[5])
  );
  NAND _142_ (
    .A(_031_),
    .B(_035_),
    .Y(_018_)
  );
  NAND _143_ (
    .A(reset_L),
    .B(_018_),
    .Y(_019_)
  );
  NOR _144_ (
    .A(data_reg0[6]),
    .B(_035_),
    .Y(_020_)
  );
  NOR _145_ (
    .A(_019_),
    .B(_020_),
    .Y(data_demux_0[6])
  );
  NAND _146_ (
    .A(_032_),
    .B(_035_),
    .Y(_021_)
  );
  NAND _147_ (
    .A(reset_L),
    .B(_021_),
    .Y(_022_)
  );
  NOR _148_ (
    .A(data_reg0[7]),
    .B(_035_),
    .Y(_023_)
  );
  NOR _149_ (
    .A(_022_),
    .B(_023_),
    .Y(data_demux_0[7])
  );
  DFF _150_ (
    .C(clk_2f),
    .D(_000_),
    .Q(selector)
  );
  DFF _151_ (
    .C(clk_2f),
    .D(data_demux_0[0]),
    .Q(data_reg0[0])
  );
  DFF _152_ (
    .C(clk_2f),
    .D(data_demux_0[1]),
    .Q(data_reg0[1])
  );
  DFF _153_ (
    .C(clk_2f),
    .D(data_demux_0[2]),
    .Q(data_reg0[2])
  );
  DFF _154_ (
    .C(clk_2f),
    .D(data_demux_0[3]),
    .Q(data_reg0[3])
  );
  DFF _155_ (
    .C(clk_2f),
    .D(data_demux_0[4]),
    .Q(data_reg0[4])
  );
  DFF _156_ (
    .C(clk_2f),
    .D(data_demux_0[5]),
    .Q(data_reg0[5])
  );
  DFF _157_ (
    .C(clk_2f),
    .D(data_demux_0[6]),
    .Q(data_reg0[6])
  );
  DFF _158_ (
    .C(clk_2f),
    .D(data_demux_0[7]),
    .Q(data_reg0[7])
  );
  DFF _159_ (
    .C(clk_2f),
    .D(data_demux_1[0]),
    .Q(data_reg1[0])
  );
  DFF _160_ (
    .C(clk_2f),
    .D(data_demux_1[1]),
    .Q(data_reg1[1])
  );
  DFF _161_ (
    .C(clk_2f),
    .D(data_demux_1[2]),
    .Q(data_reg1[2])
  );
  DFF _162_ (
    .C(clk_2f),
    .D(data_demux_1[3]),
    .Q(data_reg1[3])
  );
  DFF _163_ (
    .C(clk_2f),
    .D(data_demux_1[4]),
    .Q(data_reg1[4])
  );
  DFF _164_ (
    .C(clk_2f),
    .D(data_demux_1[5]),
    .Q(data_reg1[5])
  );
  DFF _165_ (
    .C(clk_2f),
    .D(data_demux_1[6]),
    .Q(data_reg1[6])
  );
  DFF _166_ (
    .C(clk_2f),
    .D(data_demux_1[7]),
    .Q(data_reg1[7])
  );
endmodule

module gen_clk(clk_8f, enable, clk_2f, clk_f);
  wire _00_;
  wire _01_;
  wire [1:0] _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  output clk_2f;
  input clk_8f;
  output clk_f;
  wire [1:0] counter;
  input enable;
  NOT _15_ (
    .A(enable),
    .Y(_03_)
  );
  NOR _16_ (
    .A(counter[0]),
    .B(counter[1]),
    .Y(_04_)
  );
  NAND _17_ (
    .A(enable),
    .B(_04_),
    .Y(_05_)
  );
  NOT _18_ (
    .A(_05_),
    .Y(_02_[0])
  );
  NOR _19_ (
    .A(clk_2f),
    .B(_04_),
    .Y(_06_)
  );
  NAND _20_ (
    .A(clk_f),
    .B(_06_),
    .Y(_07_)
  );
  NOT _21_ (
    .A(_07_),
    .Y(_08_)
  );
  NOR _22_ (
    .A(clk_f),
    .B(_06_),
    .Y(_09_)
  );
  NOT _23_ (
    .A(_09_),
    .Y(_10_)
  );
  NAND _24_ (
    .A(enable),
    .B(_10_),
    .Y(_11_)
  );
  NOR _25_ (
    .A(_08_),
    .B(_11_),
    .Y(_01_)
  );
  NAND _26_ (
    .A(clk_2f),
    .B(_04_),
    .Y(_12_)
  );
  NOT _27_ (
    .A(_12_),
    .Y(_13_)
  );
  NOR _28_ (
    .A(_06_),
    .B(_13_),
    .Y(_14_)
  );
  NOR _29_ (
    .A(_03_),
    .B(_14_),
    .Y(_00_)
  );
  DFF _30_ (
    .C(clk_8f),
    .D(_00_),
    .Q(clk_2f)
  );
  DFF _31_ (
    .C(clk_8f),
    .D(_01_),
    .Q(clk_f)
  );
  DFF _32_ (
    .C(clk_8f),
    .D(_02_[0]),
    .Q(counter[0])
  );
  DFF _33_ (
    .C(clk_8f),
    .D(1'h0),
    .Q(counter[1])
  );
endmodule

module phy_rxSynth(clk_8f, reset_L, in_0, in_1, enable, data_out_0_estruct, data_out_1_estruct, valid_out_0_estruct, valid_out_1_estruct);
  wire [7:0] _00_;
  wire [7:0] _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire clk_2f;
  input clk_8f;
  wire clk_f;
  wire [7:0] data_demux_0;
  wire [7:0] data_demux_1;
  output [7:0] data_out_0_estruct;
  output [7:0] data_out_1_estruct;
  wire [7:0] data_par_0;
  wire [7:0] data_par_1;
  wire [7:0] data_unstripped;
  input enable;
  input in_0;
  input in_1;
  input reset_L;
  wire valid_demux_0;
  wire valid_demux_1;
  output valid_out_0_estruct;
  output valid_out_1_estruct;
  wire valid_par_0;
  wire valid_par_1;
  wire valid_unstripped;
  NAND _22_ (
    .A(valid_demux_0),
    .B(reset_L),
    .Y(_04_)
  );
  NOT _23_ (
    .A(_04_),
    .Y(_02_)
  );
  NAND _24_ (
    .A(reset_L),
    .B(data_demux_1[0]),
    .Y(_05_)
  );
  NOT _25_ (
    .A(_05_),
    .Y(_01_[0])
  );
  NAND _26_ (
    .A(reset_L),
    .B(data_demux_1[1]),
    .Y(_06_)
  );
  NOT _27_ (
    .A(_06_),
    .Y(_01_[1])
  );
  NAND _28_ (
    .A(reset_L),
    .B(data_demux_1[2]),
    .Y(_07_)
  );
  NOT _29_ (
    .A(_07_),
    .Y(_01_[2])
  );
  NAND _30_ (
    .A(reset_L),
    .B(data_demux_1[3]),
    .Y(_08_)
  );
  NOT _31_ (
    .A(_08_),
    .Y(_01_[3])
  );
  NAND _32_ (
    .A(reset_L),
    .B(data_demux_1[4]),
    .Y(_09_)
  );
  NOT _33_ (
    .A(_09_),
    .Y(_01_[4])
  );
  NAND _34_ (
    .A(reset_L),
    .B(data_demux_1[5]),
    .Y(_10_)
  );
  NOT _35_ (
    .A(_10_),
    .Y(_01_[5])
  );
  NAND _36_ (
    .A(reset_L),
    .B(data_demux_1[6]),
    .Y(_11_)
  );
  NOT _37_ (
    .A(_11_),
    .Y(_01_[6])
  );
  NAND _38_ (
    .A(reset_L),
    .B(data_demux_1[7]),
    .Y(_12_)
  );
  NOT _39_ (
    .A(_12_),
    .Y(_01_[7])
  );
  NAND _40_ (
    .A(reset_L),
    .B(data_demux_0[0]),
    .Y(_13_)
  );
  NOT _41_ (
    .A(_13_),
    .Y(_00_[0])
  );
  NAND _42_ (
    .A(reset_L),
    .B(data_demux_0[1]),
    .Y(_14_)
  );
  NOT _43_ (
    .A(_14_),
    .Y(_00_[1])
  );
  NAND _44_ (
    .A(reset_L),
    .B(data_demux_0[2]),
    .Y(_15_)
  );
  NOT _45_ (
    .A(_15_),
    .Y(_00_[2])
  );
  NAND _46_ (
    .A(reset_L),
    .B(data_demux_0[3]),
    .Y(_16_)
  );
  NOT _47_ (
    .A(_16_),
    .Y(_00_[3])
  );
  NAND _48_ (
    .A(reset_L),
    .B(data_demux_0[4]),
    .Y(_17_)
  );
  NOT _49_ (
    .A(_17_),
    .Y(_00_[4])
  );
  NAND _50_ (
    .A(reset_L),
    .B(data_demux_0[5]),
    .Y(_18_)
  );
  NOT _51_ (
    .A(_18_),
    .Y(_00_[5])
  );
  NAND _52_ (
    .A(reset_L),
    .B(data_demux_0[6]),
    .Y(_19_)
  );
  NOT _53_ (
    .A(_19_),
    .Y(_00_[6])
  );
  NAND _54_ (
    .A(reset_L),
    .B(data_demux_0[7]),
    .Y(_20_)
  );
  NOT _55_ (
    .A(_20_),
    .Y(_00_[7])
  );
  NAND _56_ (
    .A(reset_L),
    .B(valid_demux_1),
    .Y(_21_)
  );
  NOT _57_ (
    .A(_21_),
    .Y(_03_)
  );
  DFF _58_ (
    .C(clk_2f),
    .D(_00_[0]),
    .Q(data_out_0_estruct[0])
  );
  DFF _59_ (
    .C(clk_2f),
    .D(_00_[1]),
    .Q(data_out_0_estruct[1])
  );
  DFF _60_ (
    .C(clk_2f),
    .D(_00_[2]),
    .Q(data_out_0_estruct[2])
  );
  DFF _61_ (
    .C(clk_2f),
    .D(_00_[3]),
    .Q(data_out_0_estruct[3])
  );
  DFF _62_ (
    .C(clk_2f),
    .D(_00_[4]),
    .Q(data_out_0_estruct[4])
  );
  DFF _63_ (
    .C(clk_2f),
    .D(_00_[5]),
    .Q(data_out_0_estruct[5])
  );
  DFF _64_ (
    .C(clk_2f),
    .D(_00_[6]),
    .Q(data_out_0_estruct[6])
  );
  DFF _65_ (
    .C(clk_2f),
    .D(_00_[7]),
    .Q(data_out_0_estruct[7])
  );
  DFF _66_ (
    .C(clk_2f),
    .D(_01_[0]),
    .Q(data_out_1_estruct[0])
  );
  DFF _67_ (
    .C(clk_2f),
    .D(_01_[1]),
    .Q(data_out_1_estruct[1])
  );
  DFF _68_ (
    .C(clk_2f),
    .D(_01_[2]),
    .Q(data_out_1_estruct[2])
  );
  DFF _69_ (
    .C(clk_2f),
    .D(_01_[3]),
    .Q(data_out_1_estruct[3])
  );
  DFF _70_ (
    .C(clk_2f),
    .D(_01_[4]),
    .Q(data_out_1_estruct[4])
  );
  DFF _71_ (
    .C(clk_2f),
    .D(_01_[5]),
    .Q(data_out_1_estruct[5])
  );
  DFF _72_ (
    .C(clk_2f),
    .D(_01_[6]),
    .Q(data_out_1_estruct[6])
  );
  DFF _73_ (
    .C(clk_2f),
    .D(_01_[7]),
    .Q(data_out_1_estruct[7])
  );
  DFF _74_ (
    .C(clk_2f),
    .D(_02_),
    .Q(valid_out_0_estruct)
  );
  DFF _75_ (
    .C(clk_2f),
    .D(_03_),
    .Q(valid_out_1_estruct)
  );
  byte_unstripping byte_uns (
    .clk_2f(clk_2f),
    .data_par_0(data_par_0),
    .data_par_1(data_par_1),
    .data_unstripped(data_unstripped),
    .reset_L(reset_L),
    .valid_par_0(valid_par_0),
    .valid_par_1(valid_par_1),
    .valid_unstripped(valid_unstripped)
  );
  gen_clk clocks (
    .clk_2f(clk_2f),
    .clk_8f(clk_8f),
    .clk_f(clk_f),
    .enable(enable)
  );
  demux demux0 (
    .clk_2f(clk_2f),
    .data_demux_0(data_demux_0),
    .data_demux_1(data_demux_1),
    .data_unstripped(data_unstripped),
    .reset_L(reset_L),
    .valid_demux_0(valid_demux_0),
    .valid_demux_1(valid_demux_1),
    .valid_unstripped(valid_unstripped)
  );
  serialtopar line0 (
    .clk_8f(clk_8f),
    .clk_f(clk_f),
    .data_par(data_par_0),
    .in(in_0),
    .reset_L(reset_L),
    .valid_par(valid_par_0)
  );
  serialtopar line1 (
    .clk_8f(clk_8f),
    .clk_f(clk_f),
    .data_par(data_par_1),
    .in(in_1),
    .reset_L(reset_L),
    .valid_par(valid_par_1)
  );
endmodule

module serialtopar(data_par, valid_par, clk_f, clk_8f, reset_L, in);
  wire _00_;
  wire [2:0] _01_;
  wire [7:0] _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire active;
  wire [2:0] bc_cnt;
  wire [7:0] buffer;
  input clk_8f;
  input clk_f;
  output [7:0] data_par;
  input in;
  input reset_L;
  wire [7:0] shift_reg;
  output valid_par;
  NOT _35_ (
    .A(reset_L),
    .Y(_04_)
  );
  NOT _36_ (
    .A(valid_par),
    .Y(_05_)
  );
  NOT _37_ (
    .A(buffer[1]),
    .Y(_06_)
  );
  NOR _38_ (
    .A(bc_cnt[2]),
    .B(active),
    .Y(_07_)
  );
  NOR _39_ (
    .A(_04_),
    .B(_07_),
    .Y(_00_)
  );
  NAND _40_ (
    .A(buffer[2]),
    .B(buffer[3]),
    .Y(_08_)
  );
  NAND _41_ (
    .A(buffer[4]),
    .B(buffer[6]),
    .Y(_09_)
  );
  NOR _42_ (
    .A(_08_),
    .B(_09_),
    .Y(_10_)
  );
  NOT _43_ (
    .A(_10_),
    .Y(_11_)
  );
  NOR _44_ (
    .A(in),
    .B(buffer[0]),
    .Y(_12_)
  );
  NOR _45_ (
    .A(buffer[5]),
    .B(_06_),
    .Y(_13_)
  );
  NAND _46_ (
    .A(_12_),
    .B(_13_),
    .Y(_14_)
  );
  NOR _47_ (
    .A(_11_),
    .B(_14_),
    .Y(_15_)
  );
  NAND _48_ (
    .A(reset_L),
    .B(_15_),
    .Y(_16_)
  );
  NOR _49_ (
    .A(bc_cnt[0]),
    .B(_16_),
    .Y(_01_[0])
  );
  NOR _50_ (
    .A(bc_cnt[0]),
    .B(bc_cnt[1]),
    .Y(_17_)
  );
  NOT _51_ (
    .A(_17_),
    .Y(_18_)
  );
  NAND _52_ (
    .A(bc_cnt[0]),
    .B(bc_cnt[1]),
    .Y(_19_)
  );
  NAND _53_ (
    .A(_18_),
    .B(_19_),
    .Y(_20_)
  );
  NOR _54_ (
    .A(_16_),
    .B(_20_),
    .Y(_01_[1])
  );
  NAND _55_ (
    .A(bc_cnt[2]),
    .B(_19_),
    .Y(_21_)
  );
  NOT _56_ (
    .A(_21_),
    .Y(_22_)
  );
  NOR _57_ (
    .A(bc_cnt[2]),
    .B(_19_),
    .Y(_23_)
  );
  NOR _58_ (
    .A(_22_),
    .B(_23_),
    .Y(_24_)
  );
  NOR _59_ (
    .A(_16_),
    .B(_24_),
    .Y(_01_[2])
  );
  NAND _60_ (
    .A(_05_),
    .B(_07_),
    .Y(_25_)
  );
  NAND _61_ (
    .A(reset_L),
    .B(_25_),
    .Y(_26_)
  );
  NOR _62_ (
    .A(_15_),
    .B(_26_),
    .Y(_03_)
  );
  NAND _63_ (
    .A(in),
    .B(reset_L),
    .Y(_27_)
  );
  NOT _64_ (
    .A(_27_),
    .Y(_02_[0])
  );
  NAND _65_ (
    .A(buffer[0]),
    .B(reset_L),
    .Y(_28_)
  );
  NOT _66_ (
    .A(_28_),
    .Y(_02_[1])
  );
  NAND _67_ (
    .A(reset_L),
    .B(buffer[1]),
    .Y(_29_)
  );
  NOT _68_ (
    .A(_29_),
    .Y(_02_[2])
  );
  NAND _69_ (
    .A(reset_L),
    .B(buffer[2]),
    .Y(_30_)
  );
  NOT _70_ (
    .A(_30_),
    .Y(_02_[3])
  );
  NAND _71_ (
    .A(reset_L),
    .B(buffer[3]),
    .Y(_31_)
  );
  NOT _72_ (
    .A(_31_),
    .Y(_02_[4])
  );
  NAND _73_ (
    .A(reset_L),
    .B(buffer[4]),
    .Y(_32_)
  );
  NOT _74_ (
    .A(_32_),
    .Y(_02_[5])
  );
  NAND _75_ (
    .A(buffer[5]),
    .B(reset_L),
    .Y(_33_)
  );
  NOT _76_ (
    .A(_33_),
    .Y(_02_[6])
  );
  NAND _77_ (
    .A(reset_L),
    .B(buffer[6]),
    .Y(_34_)
  );
  NOT _78_ (
    .A(_34_),
    .Y(_02_[7])
  );
  DFF _79_ (
    .C(clk_f),
    .D(_02_[0]),
    .Q(data_par[0])
  );
  DFF _80_ (
    .C(clk_f),
    .D(_02_[1]),
    .Q(data_par[1])
  );
  DFF _81_ (
    .C(clk_f),
    .D(_02_[2]),
    .Q(data_par[2])
  );
  DFF _82_ (
    .C(clk_f),
    .D(_02_[3]),
    .Q(data_par[3])
  );
  DFF _83_ (
    .C(clk_f),
    .D(_02_[4]),
    .Q(data_par[4])
  );
  DFF _84_ (
    .C(clk_f),
    .D(_02_[5]),
    .Q(data_par[5])
  );
  DFF _85_ (
    .C(clk_f),
    .D(_02_[6]),
    .Q(data_par[6])
  );
  DFF _86_ (
    .C(clk_f),
    .D(_02_[7]),
    .Q(data_par[7])
  );
  DFF _87_ (
    .C(clk_f),
    .D(_03_),
    .Q(valid_par)
  );
  DFF _88_ (
    .C(clk_f),
    .D(_00_),
    .Q(active)
  );
  DFF _89_ (
    .C(clk_f),
    .D(_01_[0]),
    .Q(bc_cnt[0])
  );
  DFF _90_ (
    .C(clk_f),
    .D(_01_[1]),
    .Q(bc_cnt[1])
  );
  DFF _91_ (
    .C(clk_f),
    .D(_01_[2]),
    .Q(bc_cnt[2])
  );
  DFF _92_ (
    .C(clk_8f),
    .D(_02_[0]),
    .Q(buffer[0])
  );
  DFF _93_ (
    .C(clk_8f),
    .D(_02_[1]),
    .Q(buffer[1])
  );
  DFF _94_ (
    .C(clk_8f),
    .D(_02_[2]),
    .Q(buffer[2])
  );
  DFF _95_ (
    .C(clk_8f),
    .D(_02_[3]),
    .Q(buffer[3])
  );
  DFF _96_ (
    .C(clk_8f),
    .D(_02_[4]),
    .Q(buffer[4])
  );
  DFF _97_ (
    .C(clk_8f),
    .D(_02_[5]),
    .Q(buffer[5])
  );
  DFF _98_ (
    .C(clk_8f),
    .D(_02_[6]),
    .Q(buffer[6])
  );
  assign shift_reg = { buffer[6:0], in };
endmodule
