/* Generated by Yosys 0.8 (git sha1 UNKNOWN, clang 6.0.0-1ubuntu2 -fPIC -Os) */
`include "./CMOS/cmos_cells.v"

module partoserialSynth(data_in, valid_in, reset, clk_8f, data_out);
  wire [3:0] _000_;
  wire _001_;
  wire [7:0] _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  input clk_8f;
  wire [3:0] contador;
  wire [7:0] data2send;
  input [7:0] data_in;
  output data_out;
  input reset;
  input valid_in;
  NOT _058_ (
    .A(contador[3]),
    .Y(_014_)
  );
  NOT _059_ (
    .A(reset),
    .Y(_015_)
  );
  NOT _060_ (
    .A(data_in[0]),
    .Y(_016_)
  );
  NOT _061_ (
    .A(data_in[1]),
    .Y(_017_)
  );
  NOT _062_ (
    .A(data_in[2]),
    .Y(_018_)
  );
  NOT _063_ (
    .A(data_in[3]),
    .Y(_019_)
  );
  NOT _064_ (
    .A(data_in[4]),
    .Y(_020_)
  );
  NOT _065_ (
    .A(data_in[5]),
    .Y(_021_)
  );
  NOT _066_ (
    .A(data_in[6]),
    .Y(_022_)
  );
  NOT _067_ (
    .A(data_in[7]),
    .Y(_023_)
  );
  NOT _068_ (
    .A(valid_in),
    .Y(_024_)
  );
  NOT _069_ (
    .A(contador[0]),
    .Y(_025_)
  );
  NOT _070_ (
    .A(contador[1]),
    .Y(_026_)
  );
  NOT _071_ (
    .A(contador[2]),
    .Y(_027_)
  );
  NOR _072_ (
    .A(_015_),
    .B(contador[0]),
    .Y(_000_[0])
  );
  NOR _073_ (
    .A(_025_),
    .B(_026_),
    .Y(_028_)
  );
  NAND _074_ (
    .A(contador[0]),
    .B(contador[1]),
    .Y(_029_)
  );
  NOR _075_ (
    .A(contador[0]),
    .B(contador[1]),
    .Y(_030_)
  );
  NOT _076_ (
    .A(_030_),
    .Y(_031_)
  );
  NAND _077_ (
    .A(reset),
    .B(_031_),
    .Y(_032_)
  );
  NOR _078_ (
    .A(_028_),
    .B(_032_),
    .Y(_000_[1])
  );
  NOR _079_ (
    .A(contador[2]),
    .B(_028_),
    .Y(_033_)
  );
  NAND _080_ (
    .A(contador[2]),
    .B(_028_),
    .Y(_034_)
  );
  NAND _081_ (
    .A(reset),
    .B(_034_),
    .Y(_035_)
  );
  NOR _082_ (
    .A(_033_),
    .B(_035_),
    .Y(_000_[2])
  );
  NOR _083_ (
    .A(_014_),
    .B(_035_),
    .Y(_000_[3])
  );
  NAND _084_ (
    .A(reset),
    .B(valid_in),
    .Y(_036_)
  );
  NOR _085_ (
    .A(_016_),
    .B(_036_),
    .Y(data2send[0])
  );
  NAND _086_ (
    .A(reset),
    .B(_024_),
    .Y(_037_)
  );
  NAND _087_ (
    .A(data_in[0]),
    .B(_037_),
    .Y(_038_)
  );
  NOT _088_ (
    .A(_038_),
    .Y(_002_[0])
  );
  NOR _089_ (
    .A(_017_),
    .B(_036_),
    .Y(data2send[1])
  );
  NAND _090_ (
    .A(data_in[1]),
    .B(_037_),
    .Y(_039_)
  );
  NOT _091_ (
    .A(_039_),
    .Y(_002_[1])
  );
  NOR _092_ (
    .A(data_in[2]),
    .B(_036_),
    .Y(_040_)
  );
  NOT _093_ (
    .A(_040_),
    .Y(data2send[2])
  );
  NAND _094_ (
    .A(_018_),
    .B(_037_),
    .Y(_002_[2])
  );
  NOR _095_ (
    .A(data_in[3]),
    .B(_036_),
    .Y(_041_)
  );
  NOT _096_ (
    .A(_041_),
    .Y(data2send[3])
  );
  NAND _097_ (
    .A(_019_),
    .B(_037_),
    .Y(_002_[3])
  );
  NOR _098_ (
    .A(data_in[4]),
    .B(_036_),
    .Y(_042_)
  );
  NOT _099_ (
    .A(_042_),
    .Y(data2send[4])
  );
  NAND _100_ (
    .A(_020_),
    .B(_037_),
    .Y(_002_[4])
  );
  NOR _101_ (
    .A(data_in[5]),
    .B(_036_),
    .Y(_043_)
  );
  NOT _102_ (
    .A(_043_),
    .Y(data2send[5])
  );
  NAND _103_ (
    .A(_021_),
    .B(_037_),
    .Y(_002_[5])
  );
  NOR _104_ (
    .A(_022_),
    .B(_036_),
    .Y(data2send[6])
  );
  NAND _105_ (
    .A(data_in[6]),
    .B(_037_),
    .Y(_044_)
  );
  NOT _106_ (
    .A(_044_),
    .Y(_002_[6])
  );
  NOR _107_ (
    .A(data_in[7]),
    .B(_036_),
    .Y(_045_)
  );
  NOT _108_ (
    .A(_045_),
    .Y(data2send[7])
  );
  NAND _109_ (
    .A(_023_),
    .B(_037_),
    .Y(_002_[7])
  );
  NOR _110_ (
    .A(_027_),
    .B(_041_),
    .Y(_046_)
  );
  NOR _111_ (
    .A(contador[2]),
    .B(_045_),
    .Y(_047_)
  );
  NOR _112_ (
    .A(_046_),
    .B(_047_),
    .Y(_048_)
  );
  NAND _113_ (
    .A(_030_),
    .B(_048_),
    .Y(_049_)
  );
  NOR _114_ (
    .A(_027_),
    .B(_040_),
    .Y(_050_)
  );
  NAND _115_ (
    .A(contador[0]),
    .B(_026_),
    .Y(_051_)
  );
  NAND _116_ (
    .A(_027_),
    .B(data2send[6]),
    .Y(_052_)
  );
  NOR _117_ (
    .A(_050_),
    .B(_051_),
    .Y(_053_)
  );
  NAND _118_ (
    .A(_052_),
    .B(_053_),
    .Y(_054_)
  );
  NAND _119_ (
    .A(_049_),
    .B(_054_),
    .Y(_055_)
  );
  NOR _120_ (
    .A(contador[2]),
    .B(_043_),
    .Y(_056_)
  );
  NAND _121_ (
    .A(contador[2]),
    .B(data2send[1]),
    .Y(_057_)
  );
  NAND _122_ (
    .A(contador[1]),
    .B(_057_),
    .Y(_003_)
  );
  NOT _123_ (
    .A(_003_),
    .Y(_004_)
  );
  NOR _124_ (
    .A(contador[0]),
    .B(_056_),
    .Y(_005_)
  );
  NAND _125_ (
    .A(_004_),
    .B(_005_),
    .Y(_006_)
  );
  NOR _126_ (
    .A(_034_),
    .B(data2send[0]),
    .Y(_007_)
  );
  NOR _127_ (
    .A(contador[3]),
    .B(_015_),
    .Y(_008_)
  );
  NOR _128_ (
    .A(contador[2]),
    .B(_029_),
    .Y(_009_)
  );
  NAND _129_ (
    .A(_042_),
    .B(_009_),
    .Y(_010_)
  );
  NAND _130_ (
    .A(_008_),
    .B(_010_),
    .Y(_011_)
  );
  NOR _131_ (
    .A(_007_),
    .B(_011_),
    .Y(_012_)
  );
  NAND _132_ (
    .A(_006_),
    .B(_012_),
    .Y(_013_)
  );
  NOR _133_ (
    .A(_055_),
    .B(_013_),
    .Y(_001_)
  );
  DFF _134_ (
    .C(clk_8f),
    .D(_001_),
    .Q(data_out)
  );
  DFF _135_ (
    .C(clk_8f),
    .D(_002_[0]),
    .Q(data2send[0])
  );
  DFF _136_ (
    .C(clk_8f),
    .D(_002_[1]),
    .Q(data2send[1])
  );
  DFF _137_ (
    .C(clk_8f),
    .D(_002_[2]),
    .Q(data2send[2])
  );
  DFF _138_ (
    .C(clk_8f),
    .D(_002_[3]),
    .Q(data2send[3])
  );
  DFF _139_ (
    .C(clk_8f),
    .D(_002_[4]),
    .Q(data2send[4])
  );
  DFF _140_ (
    .C(clk_8f),
    .D(_002_[5]),
    .Q(data2send[5])
  );
  DFF _141_ (
    .C(clk_8f),
    .D(_002_[6]),
    .Q(data2send[6])
  );
  DFF _142_ (
    .C(clk_8f),
    .D(_002_[7]),
    .Q(data2send[7])
  );
  DFF _143_ (
    .C(clk_8f),
    .D(_000_[0]),
    .Q(contador[0])
  );
  DFF _144_ (
    .C(clk_8f),
    .D(_000_[1]),
    .Q(contador[1])
  );
  DFF _145_ (
    .C(clk_8f),
    .D(_000_[2]),
    .Q(contador[2])
  );
  DFF _146_ (
    .C(clk_8f),
    .D(_000_[3]),
    .Q(contador[3])
  );
endmodule
