/* Generated by Yosys 0.8 (git sha1 UNKNOWN, clang 6.0.0-1ubuntu2 -fPIC -Os) */
`include "./CMOS/cmos_cells.v"

module partoserialSynth(data_in, valid_in, reset, clk_8f, data_out);
  wire [3:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  input clk_8f;
  wire [3:0] contador;
  input [7:0] data_in;
  output data_out;
  input reset;
  input valid_in;
  NOT _46_ (
    .A(contador[3]),
    .Y(_02_)
  );
  NOT _47_ (
    .A(reset),
    .Y(_03_)
  );
  NOT _48_ (
    .A(data_in[6]),
    .Y(_04_)
  );
  NOT _49_ (
    .A(data_in[7]),
    .Y(_05_)
  );
  NOT _50_ (
    .A(contador[0]),
    .Y(_06_)
  );
  NOT _51_ (
    .A(contador[1]),
    .Y(_07_)
  );
  NOT _52_ (
    .A(contador[2]),
    .Y(_08_)
  );
  NOR _53_ (
    .A(_03_),
    .B(contador[0]),
    .Y(_00_[0])
  );
  NOR _54_ (
    .A(_06_),
    .B(_07_),
    .Y(_09_)
  );
  NOR _55_ (
    .A(contador[0]),
    .B(contador[1]),
    .Y(_10_)
  );
  NOT _56_ (
    .A(_10_),
    .Y(_11_)
  );
  NAND _57_ (
    .A(reset),
    .B(_11_),
    .Y(_12_)
  );
  NOR _58_ (
    .A(_09_),
    .B(_12_),
    .Y(_00_[1])
  );
  NOR _59_ (
    .A(contador[2]),
    .B(_09_),
    .Y(_13_)
  );
  NAND _60_ (
    .A(contador[2]),
    .B(_09_),
    .Y(_14_)
  );
  NAND _61_ (
    .A(reset),
    .B(_14_),
    .Y(_15_)
  );
  NOR _62_ (
    .A(_13_),
    .B(_15_),
    .Y(_00_[2])
  );
  NOR _63_ (
    .A(_02_),
    .B(_15_),
    .Y(_00_[3])
  );
  NAND _64_ (
    .A(reset),
    .B(valid_in),
    .Y(_16_)
  );
  NOR _65_ (
    .A(data_in[4]),
    .B(_16_),
    .Y(_17_)
  );
  NOR _66_ (
    .A(contador[2]),
    .B(_17_),
    .Y(_18_)
  );
  NOR _67_ (
    .A(_08_),
    .B(_16_),
    .Y(_19_)
  );
  NOT _68_ (
    .A(_19_),
    .Y(_20_)
  );
  NAND _69_ (
    .A(data_in[0]),
    .B(_19_),
    .Y(_21_)
  );
  NAND _70_ (
    .A(contador[1]),
    .B(_21_),
    .Y(_22_)
  );
  NOR _71_ (
    .A(_18_),
    .B(_22_),
    .Y(_23_)
  );
  NOR _72_ (
    .A(data_in[2]),
    .B(_20_),
    .Y(_24_)
  );
  NOR _73_ (
    .A(_04_),
    .B(_16_),
    .Y(_25_)
  );
  NOR _74_ (
    .A(contador[2]),
    .B(_25_),
    .Y(_26_)
  );
  NOR _75_ (
    .A(_24_),
    .B(_26_),
    .Y(_27_)
  );
  NOR _76_ (
    .A(contador[1]),
    .B(_27_),
    .Y(_28_)
  );
  NOR _77_ (
    .A(_23_),
    .B(_28_),
    .Y(_29_)
  );
  NOR _78_ (
    .A(_06_),
    .B(_29_),
    .Y(_30_)
  );
  NOR _79_ (
    .A(contador[1]),
    .B(_16_),
    .Y(_31_)
  );
  NOR _80_ (
    .A(_05_),
    .B(contador[2]),
    .Y(_32_)
  );
  NAND _81_ (
    .A(data_in[3]),
    .B(contador[2]),
    .Y(_33_)
  );
  NOT _82_ (
    .A(_33_),
    .Y(_34_)
  );
  NOR _83_ (
    .A(_32_),
    .B(_34_),
    .Y(_35_)
  );
  NAND _84_ (
    .A(_31_),
    .B(_35_),
    .Y(_36_)
  );
  NOR _85_ (
    .A(data_in[5]),
    .B(_16_),
    .Y(_37_)
  );
  NOR _86_ (
    .A(contador[2]),
    .B(_37_),
    .Y(_38_)
  );
  NAND _87_ (
    .A(data_in[1]),
    .B(_19_),
    .Y(_39_)
  );
  NOR _88_ (
    .A(_07_),
    .B(_38_),
    .Y(_40_)
  );
  NAND _89_ (
    .A(_39_),
    .B(_40_),
    .Y(_41_)
  );
  NAND _90_ (
    .A(_36_),
    .B(_41_),
    .Y(_42_)
  );
  NAND _91_ (
    .A(_06_),
    .B(_42_),
    .Y(_43_)
  );
  NOR _92_ (
    .A(contador[3]),
    .B(_03_),
    .Y(_44_)
  );
  NAND _93_ (
    .A(_43_),
    .B(_44_),
    .Y(_45_)
  );
  NOR _94_ (
    .A(_30_),
    .B(_45_),
    .Y(_01_)
  );
  DFF _95_ (
    .C(clk_8f),
    .D(_01_),
    .Q(data_out)
  );
  DFF _96_ (
    .C(clk_8f),
    .D(_00_[0]),
    .Q(contador[0])
  );
  DFF _97_ (
    .C(clk_8f),
    .D(_00_[1]),
    .Q(contador[1])
  );
  DFF _98_ (
    .C(clk_8f),
    .D(_00_[2]),
    .Q(contador[2])
  );
  DFF _99_ (
    .C(clk_8f),
    .D(_00_[3]),
    .Q(contador[3])
  );
endmodule
