/* Generated by Yosys 0.8 (git sha1 UNKNOWN, clang 6.0.0-1ubuntu2 -fPIC -Os) */

module bs(data_in, valid_in, reset, clk_2f, lane_0_cond, valid_0_cond, lane_1_cond, valid_1_cond);
  wire [7:0] _000_;
  wire [7:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  input clk_2f;
  input [7:0] data_in;
  wire [7:0] l0;
  wire [7:0] l1;
  output [7:0] lane_0_cond;
  output [7:0] lane_1_cond;
  input reset;
  wire selector;
  output valid_0_cond;
  output valid_1_cond;
  input valid_in;
  wire validflop;
  NOT _076_ (
    .A(reset),
    .Y(_045_)
  );
  NOT _077_ (
    .A(valid_in),
    .Y(_046_)
  );
  NOT _078_ (
    .A(validflop),
    .Y(_047_)
  );
  NOT _079_ (
    .A(data_in[0]),
    .Y(_048_)
  );
  NOT _080_ (
    .A(data_in[1]),
    .Y(_049_)
  );
  NOT _081_ (
    .A(data_in[2]),
    .Y(_050_)
  );
  NOT _082_ (
    .A(data_in[3]),
    .Y(_051_)
  );
  NOT _083_ (
    .A(data_in[4]),
    .Y(_052_)
  );
  NOT _084_ (
    .A(data_in[5]),
    .Y(_053_)
  );
  NOT _085_ (
    .A(data_in[6]),
    .Y(_054_)
  );
  NOT _086_ (
    .A(data_in[7]),
    .Y(_055_)
  );
  NOT _087_ (
    .A(l0[0]),
    .Y(_056_)
  );
  NOT _088_ (
    .A(l0[1]),
    .Y(_057_)
  );
  NOT _089_ (
    .A(l0[2]),
    .Y(_058_)
  );
  NOT _090_ (
    .A(l0[3]),
    .Y(_059_)
  );
  NOT _091_ (
    .A(l0[4]),
    .Y(_060_)
  );
  NOT _092_ (
    .A(l0[5]),
    .Y(_061_)
  );
  NOT _093_ (
    .A(l0[6]),
    .Y(_062_)
  );
  NOT _094_ (
    .A(l0[7]),
    .Y(_063_)
  );
  NOR _095_ (
    .A(selector),
    .B(l1[1]),
    .Y(_064_)
  );
  NOR _096_ (
    .A(_045_),
    .B(selector),
    .Y(_002_)
  );
  NAND _097_ (
    .A(selector),
    .B(_049_),
    .Y(_065_)
  );
  NAND _098_ (
    .A(reset),
    .B(_065_),
    .Y(_066_)
  );
  NOR _099_ (
    .A(_064_),
    .B(_066_),
    .Y(lane_1_cond[1])
  );
  NOR _100_ (
    .A(selector),
    .B(l1[2]),
    .Y(_067_)
  );
  NAND _101_ (
    .A(selector),
    .B(_050_),
    .Y(_068_)
  );
  NAND _102_ (
    .A(reset),
    .B(_068_),
    .Y(_069_)
  );
  NOR _103_ (
    .A(_067_),
    .B(_069_),
    .Y(lane_1_cond[2])
  );
  NOR _104_ (
    .A(selector),
    .B(l1[3]),
    .Y(_070_)
  );
  NAND _105_ (
    .A(selector),
    .B(_051_),
    .Y(_071_)
  );
  NAND _106_ (
    .A(reset),
    .B(_071_),
    .Y(_072_)
  );
  NOR _107_ (
    .A(_070_),
    .B(_072_),
    .Y(lane_1_cond[3])
  );
  NOR _108_ (
    .A(selector),
    .B(l1[4]),
    .Y(_073_)
  );
  NAND _109_ (
    .A(selector),
    .B(_052_),
    .Y(_074_)
  );
  NAND _110_ (
    .A(reset),
    .B(_074_),
    .Y(_075_)
  );
  NOR _111_ (
    .A(_073_),
    .B(_075_),
    .Y(lane_1_cond[4])
  );
  NOR _112_ (
    .A(selector),
    .B(l1[5]),
    .Y(_004_)
  );
  NAND _113_ (
    .A(selector),
    .B(_053_),
    .Y(_005_)
  );
  NAND _114_ (
    .A(reset),
    .B(_005_),
    .Y(_006_)
  );
  NOR _115_ (
    .A(_004_),
    .B(_006_),
    .Y(lane_1_cond[5])
  );
  NOR _116_ (
    .A(selector),
    .B(l1[6]),
    .Y(_007_)
  );
  NAND _117_ (
    .A(selector),
    .B(_054_),
    .Y(_008_)
  );
  NAND _118_ (
    .A(reset),
    .B(_008_),
    .Y(_009_)
  );
  NOR _119_ (
    .A(_007_),
    .B(_009_),
    .Y(lane_1_cond[6])
  );
  NOR _120_ (
    .A(selector),
    .B(l1[7]),
    .Y(_010_)
  );
  NAND _121_ (
    .A(selector),
    .B(_055_),
    .Y(_011_)
  );
  NAND _122_ (
    .A(reset),
    .B(_011_),
    .Y(_012_)
  );
  NOR _123_ (
    .A(_010_),
    .B(_012_),
    .Y(lane_1_cond[7])
  );
  NOR _124_ (
    .A(selector),
    .B(data_in[0]),
    .Y(_013_)
  );
  NAND _125_ (
    .A(selector),
    .B(_056_),
    .Y(_014_)
  );
  NAND _126_ (
    .A(reset),
    .B(_014_),
    .Y(_015_)
  );
  NOR _127_ (
    .A(_013_),
    .B(_015_),
    .Y(lane_0_cond[0])
  );
  NOR _128_ (
    .A(selector),
    .B(data_in[1]),
    .Y(_016_)
  );
  NAND _129_ (
    .A(selector),
    .B(_057_),
    .Y(_017_)
  );
  NAND _130_ (
    .A(reset),
    .B(_017_),
    .Y(_018_)
  );
  NOR _131_ (
    .A(_016_),
    .B(_018_),
    .Y(lane_0_cond[1])
  );
  NOR _132_ (
    .A(selector),
    .B(data_in[2]),
    .Y(_019_)
  );
  NAND _133_ (
    .A(selector),
    .B(_058_),
    .Y(_020_)
  );
  NAND _134_ (
    .A(reset),
    .B(_020_),
    .Y(_021_)
  );
  NOR _135_ (
    .A(_019_),
    .B(_021_),
    .Y(lane_0_cond[2])
  );
  NOR _136_ (
    .A(selector),
    .B(data_in[3]),
    .Y(_022_)
  );
  NAND _137_ (
    .A(selector),
    .B(_059_),
    .Y(_023_)
  );
  NAND _138_ (
    .A(reset),
    .B(_023_),
    .Y(_024_)
  );
  NOR _139_ (
    .A(_022_),
    .B(_024_),
    .Y(lane_0_cond[3])
  );
  NOR _140_ (
    .A(selector),
    .B(data_in[4]),
    .Y(_025_)
  );
  NAND _141_ (
    .A(selector),
    .B(_060_),
    .Y(_026_)
  );
  NAND _142_ (
    .A(reset),
    .B(_026_),
    .Y(_027_)
  );
  NOR _143_ (
    .A(_025_),
    .B(_027_),
    .Y(lane_0_cond[4])
  );
  NOR _144_ (
    .A(selector),
    .B(data_in[5]),
    .Y(_028_)
  );
  NAND _145_ (
    .A(selector),
    .B(_061_),
    .Y(_029_)
  );
  NAND _146_ (
    .A(reset),
    .B(_029_),
    .Y(_030_)
  );
  NOR _147_ (
    .A(_028_),
    .B(_030_),
    .Y(lane_0_cond[5])
  );
  NOR _148_ (
    .A(selector),
    .B(data_in[6]),
    .Y(_031_)
  );
  NAND _149_ (
    .A(selector),
    .B(_062_),
    .Y(_032_)
  );
  NAND _150_ (
    .A(reset),
    .B(_032_),
    .Y(_033_)
  );
  NOR _151_ (
    .A(_031_),
    .B(_033_),
    .Y(lane_0_cond[6])
  );
  NOR _152_ (
    .A(selector),
    .B(data_in[7]),
    .Y(_034_)
  );
  NAND _153_ (
    .A(selector),
    .B(_063_),
    .Y(_035_)
  );
  NAND _154_ (
    .A(reset),
    .B(_035_),
    .Y(_036_)
  );
  NOR _155_ (
    .A(_034_),
    .B(_036_),
    .Y(lane_0_cond[7])
  );
  NOR _156_ (
    .A(_045_),
    .B(_046_),
    .Y(_003_)
  );
  NOR _157_ (
    .A(validflop),
    .B(selector),
    .Y(_037_)
  );
  NOR _158_ (
    .A(_002_),
    .B(_003_),
    .Y(_038_)
  );
  NOR _159_ (
    .A(_037_),
    .B(_038_),
    .Y(valid_1_cond)
  );
  NOR _160_ (
    .A(selector),
    .B(l1[0]),
    .Y(_039_)
  );
  NAND _161_ (
    .A(selector),
    .B(_048_),
    .Y(_040_)
  );
  NAND _162_ (
    .A(reset),
    .B(_040_),
    .Y(_041_)
  );
  NOR _163_ (
    .A(_039_),
    .B(_041_),
    .Y(lane_1_cond[0])
  );
  NOR _164_ (
    .A(valid_in),
    .B(selector),
    .Y(_042_)
  );
  NAND _165_ (
    .A(_047_),
    .B(selector),
    .Y(_043_)
  );
  NAND _166_ (
    .A(reset),
    .B(_043_),
    .Y(_044_)
  );
  NOR _167_ (
    .A(_042_),
    .B(_044_),
    .Y(valid_0_cond)
  );
  NOR _168_ (
    .A(_064_),
    .B(_066_),
    .Y(_001_[1])
  );
  NOR _169_ (
    .A(_067_),
    .B(_069_),
    .Y(_001_[2])
  );
  NOR _170_ (
    .A(_070_),
    .B(_072_),
    .Y(_001_[3])
  );
  NOR _171_ (
    .A(_073_),
    .B(_075_),
    .Y(_001_[4])
  );
  NOR _172_ (
    .A(_004_),
    .B(_006_),
    .Y(_001_[5])
  );
  NOR _173_ (
    .A(_007_),
    .B(_009_),
    .Y(_001_[6])
  );
  NOR _174_ (
    .A(_010_),
    .B(_012_),
    .Y(_001_[7])
  );
  NOR _175_ (
    .A(_013_),
    .B(_015_),
    .Y(_000_[0])
  );
  NOR _176_ (
    .A(_016_),
    .B(_018_),
    .Y(_000_[1])
  );
  NOR _177_ (
    .A(_019_),
    .B(_021_),
    .Y(_000_[2])
  );
  NOR _178_ (
    .A(_022_),
    .B(_024_),
    .Y(_000_[3])
  );
  NOR _179_ (
    .A(_025_),
    .B(_027_),
    .Y(_000_[4])
  );
  NOR _180_ (
    .A(_028_),
    .B(_030_),
    .Y(_000_[5])
  );
  NOR _181_ (
    .A(_031_),
    .B(_033_),
    .Y(_000_[6])
  );
  NOR _182_ (
    .A(_034_),
    .B(_036_),
    .Y(_000_[7])
  );
  NOR _183_ (
    .A(_039_),
    .B(_041_),
    .Y(_001_[0])
  );
  DFF _184_ (
    .C(clk_2f),
    .D(_002_),
    .Q(selector)
  );
  DFF _185_ (
    .C(clk_2f),
    .D(_003_),
    .Q(validflop)
  );
  DFF _186_ (
    .C(clk_2f),
    .D(_000_[0]),
    .Q(l0[0])
  );
  DFF _187_ (
    .C(clk_2f),
    .D(_000_[1]),
    .Q(l0[1])
  );
  DFF _188_ (
    .C(clk_2f),
    .D(_000_[2]),
    .Q(l0[2])
  );
  DFF _189_ (
    .C(clk_2f),
    .D(_000_[3]),
    .Q(l0[3])
  );
  DFF _190_ (
    .C(clk_2f),
    .D(_000_[4]),
    .Q(l0[4])
  );
  DFF _191_ (
    .C(clk_2f),
    .D(_000_[5]),
    .Q(l0[5])
  );
  DFF _192_ (
    .C(clk_2f),
    .D(_000_[6]),
    .Q(l0[6])
  );
  DFF _193_ (
    .C(clk_2f),
    .D(_000_[7]),
    .Q(l0[7])
  );
  DFF _194_ (
    .C(clk_2f),
    .D(_001_[0]),
    .Q(l1[0])
  );
  DFF _195_ (
    .C(clk_2f),
    .D(_001_[1]),
    .Q(l1[1])
  );
  DFF _196_ (
    .C(clk_2f),
    .D(_001_[2]),
    .Q(l1[2])
  );
  DFF _197_ (
    .C(clk_2f),
    .D(_001_[3]),
    .Q(l1[3])
  );
  DFF _198_ (
    .C(clk_2f),
    .D(_001_[4]),
    .Q(l1[4])
  );
  DFF _199_ (
    .C(clk_2f),
    .D(_001_[5]),
    .Q(l1[5])
  );
  DFF _200_ (
    .C(clk_2f),
    .D(_001_[6]),
    .Q(l1[6])
  );
  DFF _201_ (
    .C(clk_2f),
    .D(_001_[7]),
    .Q(l1[7])
  );
endmodule

module gen_clk(clk_8f, rst, enb, clk_2f, clk_f);
  wire _00_;
  wire _01_;
  wire [1:0] _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  output clk_2f;
  input clk_8f;
  output clk_f;
  wire [0:1] counter;
  input enb;
  input rst;
  NOT _20_ (
    .A(counter[0]),
    .Y(_03_)
  );
  NOT _21_ (
    .A(rst),
    .Y(_04_)
  );
  NAND _22_ (
    .A(counter[1]),
    .B(enb),
    .Y(_05_)
  );
  NOT _23_ (
    .A(_05_),
    .Y(_06_)
  );
  NOR _24_ (
    .A(counter[1]),
    .B(enb),
    .Y(_07_)
  );
  NOT _25_ (
    .A(_07_),
    .Y(_08_)
  );
  NAND _26_ (
    .A(_05_),
    .B(_08_),
    .Y(_09_)
  );
  NAND _27_ (
    .A(_04_),
    .B(_09_),
    .Y(_02_[0])
  );
  NAND _28_ (
    .A(counter[0]),
    .B(_06_),
    .Y(_10_)
  );
  NAND _29_ (
    .A(_03_),
    .B(_05_),
    .Y(_11_)
  );
  NAND _30_ (
    .A(_10_),
    .B(_11_),
    .Y(_12_)
  );
  NAND _31_ (
    .A(_04_),
    .B(_12_),
    .Y(_02_[1])
  );
  NOR _32_ (
    .A(clk_2f),
    .B(_10_),
    .Y(_13_)
  );
  NOR _33_ (
    .A(clk_f),
    .B(_13_),
    .Y(_14_)
  );
  NAND _34_ (
    .A(clk_f),
    .B(_13_),
    .Y(_15_)
  );
  NAND _35_ (
    .A(_04_),
    .B(_15_),
    .Y(_16_)
  );
  NOR _36_ (
    .A(_14_),
    .B(_16_),
    .Y(_01_)
  );
  NAND _37_ (
    .A(clk_2f),
    .B(_10_),
    .Y(_17_)
  );
  NOT _38_ (
    .A(_17_),
    .Y(_18_)
  );
  NOR _39_ (
    .A(_13_),
    .B(_18_),
    .Y(_19_)
  );
  NOR _40_ (
    .A(rst),
    .B(_19_),
    .Y(_00_)
  );
  DFF _41_ (
    .C(clk_8f),
    .D(_00_),
    .Q(clk_2f)
  );
  DFF _42_ (
    .C(clk_8f),
    .D(_01_),
    .Q(clk_f)
  );
  DFF _43_ (
    .C(clk_8f),
    .D(_02_[0]),
    .Q(counter[1])
  );
  DFF _44_ (
    .C(clk_8f),
    .D(_02_[1]),
    .Q(counter[0])
  );
endmodule

module mux(data_out, valid_out, clk, reset_L, valid_in_0, data_in_0, valid_in_1, data_in_1);
  wire _000_;
  wire [7:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire channel;
  input clk;
  input [7:0] data_in_0;
  input [7:0] data_in_1;
  output [7:0] data_out;
  wire ignore;
  input reset_L;
  wire selector;
  input valid_in_0;
  input valid_in_1;
  output valid_out;
  NOT _054_ (
    .A(valid_in_0),
    .Y(_004_)
  );
  NOT _055_ (
    .A(selector),
    .Y(_005_)
  );
  NOT _056_ (
    .A(reset_L),
    .Y(_006_)
  );
  NOT _057_ (
    .A(data_in_0[0]),
    .Y(_007_)
  );
  NOT _058_ (
    .A(data_in_0[1]),
    .Y(_008_)
  );
  NOT _059_ (
    .A(data_in_0[2]),
    .Y(_009_)
  );
  NOT _060_ (
    .A(data_in_0[3]),
    .Y(_010_)
  );
  NOT _061_ (
    .A(data_in_0[4]),
    .Y(_011_)
  );
  NOT _062_ (
    .A(data_in_0[5]),
    .Y(_012_)
  );
  NOT _063_ (
    .A(data_in_0[6]),
    .Y(_013_)
  );
  NOT _064_ (
    .A(data_in_0[7]),
    .Y(_014_)
  );
  NAND _065_ (
    .A(valid_in_0),
    .B(valid_in_1),
    .Y(_015_)
  );
  NOR _066_ (
    .A(valid_out),
    .B(_015_),
    .Y(_016_)
  );
  NAND _067_ (
    .A(selector),
    .B(_016_),
    .Y(_017_)
  );
  NAND _068_ (
    .A(valid_out),
    .B(channel),
    .Y(_018_)
  );
  NAND _069_ (
    .A(valid_in_0),
    .B(_018_),
    .Y(_019_)
  );
  NAND _070_ (
    .A(valid_in_1),
    .B(_019_),
    .Y(_020_)
  );
  NAND _071_ (
    .A(_017_),
    .B(_020_),
    .Y(_021_)
  );
  NOT _072_ (
    .A(_021_),
    .Y(_022_)
  );
  NOR _073_ (
    .A(_006_),
    .B(_022_),
    .Y(_000_)
  );
  NOR _074_ (
    .A(selector),
    .B(_016_),
    .Y(_023_)
  );
  NAND _075_ (
    .A(reset_L),
    .B(_017_),
    .Y(_024_)
  );
  NOR _076_ (
    .A(_023_),
    .B(_024_),
    .Y(_003_)
  );
  NOR _077_ (
    .A(valid_in_0),
    .B(valid_in_1),
    .Y(_025_)
  );
  NOR _078_ (
    .A(_006_),
    .B(_025_),
    .Y(_002_)
  );
  NAND _079_ (
    .A(data_in_1[0]),
    .B(_000_),
    .Y(_026_)
  );
  NOR _080_ (
    .A(_004_),
    .B(valid_in_1),
    .Y(_027_)
  );
  NOR _081_ (
    .A(valid_out),
    .B(_005_),
    .Y(_028_)
  );
  NOR _082_ (
    .A(_019_),
    .B(_028_),
    .Y(_029_)
  );
  NOR _083_ (
    .A(_027_),
    .B(_029_),
    .Y(_030_)
  );
  NOR _084_ (
    .A(_007_),
    .B(_030_),
    .Y(_031_)
  );
  NAND _085_ (
    .A(reset_L),
    .B(_031_),
    .Y(_032_)
  );
  NAND _086_ (
    .A(_026_),
    .B(_032_),
    .Y(_001_[0])
  );
  NAND _087_ (
    .A(data_in_1[1]),
    .B(_000_),
    .Y(_033_)
  );
  NOR _088_ (
    .A(_008_),
    .B(_030_),
    .Y(_034_)
  );
  NAND _089_ (
    .A(reset_L),
    .B(_034_),
    .Y(_035_)
  );
  NAND _090_ (
    .A(_033_),
    .B(_035_),
    .Y(_001_[1])
  );
  NAND _091_ (
    .A(data_in_1[2]),
    .B(_000_),
    .Y(_036_)
  );
  NOR _092_ (
    .A(_009_),
    .B(_030_),
    .Y(_037_)
  );
  NAND _093_ (
    .A(reset_L),
    .B(_037_),
    .Y(_038_)
  );
  NAND _094_ (
    .A(_036_),
    .B(_038_),
    .Y(_001_[2])
  );
  NAND _095_ (
    .A(data_in_1[3]),
    .B(_000_),
    .Y(_039_)
  );
  NOR _096_ (
    .A(_010_),
    .B(_030_),
    .Y(_040_)
  );
  NAND _097_ (
    .A(reset_L),
    .B(_040_),
    .Y(_041_)
  );
  NAND _098_ (
    .A(_039_),
    .B(_041_),
    .Y(_001_[3])
  );
  NAND _099_ (
    .A(data_in_1[4]),
    .B(_000_),
    .Y(_042_)
  );
  NOR _100_ (
    .A(_011_),
    .B(_030_),
    .Y(_043_)
  );
  NAND _101_ (
    .A(reset_L),
    .B(_043_),
    .Y(_044_)
  );
  NAND _102_ (
    .A(_042_),
    .B(_044_),
    .Y(_001_[4])
  );
  NAND _103_ (
    .A(data_in_1[5]),
    .B(_000_),
    .Y(_045_)
  );
  NOR _104_ (
    .A(_012_),
    .B(_030_),
    .Y(_046_)
  );
  NAND _105_ (
    .A(reset_L),
    .B(_046_),
    .Y(_047_)
  );
  NAND _106_ (
    .A(_045_),
    .B(_047_),
    .Y(_001_[5])
  );
  NAND _107_ (
    .A(data_in_1[6]),
    .B(_000_),
    .Y(_048_)
  );
  NOR _108_ (
    .A(_013_),
    .B(_030_),
    .Y(_049_)
  );
  NAND _109_ (
    .A(reset_L),
    .B(_049_),
    .Y(_050_)
  );
  NAND _110_ (
    .A(_048_),
    .B(_050_),
    .Y(_001_[6])
  );
  NAND _111_ (
    .A(data_in_1[7]),
    .B(_000_),
    .Y(_051_)
  );
  NOR _112_ (
    .A(_014_),
    .B(_030_),
    .Y(_052_)
  );
  NAND _113_ (
    .A(reset_L),
    .B(_052_),
    .Y(_053_)
  );
  NAND _114_ (
    .A(_051_),
    .B(_053_),
    .Y(_001_[7])
  );
  DFF _115_ (
    .C(clk),
    .D(_001_[0]),
    .Q(data_out[0])
  );
  DFF _116_ (
    .C(clk),
    .D(_001_[1]),
    .Q(data_out[1])
  );
  DFF _117_ (
    .C(clk),
    .D(_001_[2]),
    .Q(data_out[2])
  );
  DFF _118_ (
    .C(clk),
    .D(_001_[3]),
    .Q(data_out[3])
  );
  DFF _119_ (
    .C(clk),
    .D(_001_[4]),
    .Q(data_out[4])
  );
  DFF _120_ (
    .C(clk),
    .D(_001_[5]),
    .Q(data_out[5])
  );
  DFF _121_ (
    .C(clk),
    .D(_001_[6]),
    .Q(data_out[6])
  );
  DFF _122_ (
    .C(clk),
    .D(_001_[7]),
    .Q(data_out[7])
  );
  DFF _123_ (
    .C(clk),
    .D(_002_),
    .Q(valid_out)
  );
  DFF _124_ (
    .C(clk),
    .D(_003_),
    .Q(selector)
  );
  DFF _125_ (
    .C(clk),
    .D(_000_),
    .Q(channel)
  );
  assign ignore = valid_out;
endmodule

module partoserial(data_in, valid_in, reset, clk_8f, data_out);
  wire [3:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  input clk_8f;
  wire [3:0] contador;
  input [7:0] data_in;
  output data_out;
  input reset;
  input valid_in;
  NOT _46_ (
    .A(contador[3]),
    .Y(_02_)
  );
  NOT _47_ (
    .A(reset),
    .Y(_03_)
  );
  NOT _48_ (
    .A(data_in[6]),
    .Y(_04_)
  );
  NOT _49_ (
    .A(data_in[7]),
    .Y(_05_)
  );
  NOT _50_ (
    .A(contador[0]),
    .Y(_06_)
  );
  NOT _51_ (
    .A(contador[1]),
    .Y(_07_)
  );
  NOT _52_ (
    .A(contador[2]),
    .Y(_08_)
  );
  NOR _53_ (
    .A(_03_),
    .B(contador[0]),
    .Y(_00_[0])
  );
  NOR _54_ (
    .A(_06_),
    .B(_07_),
    .Y(_09_)
  );
  NOR _55_ (
    .A(contador[0]),
    .B(contador[1]),
    .Y(_10_)
  );
  NOT _56_ (
    .A(_10_),
    .Y(_11_)
  );
  NAND _57_ (
    .A(reset),
    .B(_11_),
    .Y(_12_)
  );
  NOR _58_ (
    .A(_09_),
    .B(_12_),
    .Y(_00_[1])
  );
  NOR _59_ (
    .A(contador[2]),
    .B(_09_),
    .Y(_13_)
  );
  NAND _60_ (
    .A(contador[2]),
    .B(_09_),
    .Y(_14_)
  );
  NAND _61_ (
    .A(reset),
    .B(_14_),
    .Y(_15_)
  );
  NOR _62_ (
    .A(_13_),
    .B(_15_),
    .Y(_00_[2])
  );
  NOR _63_ (
    .A(_02_),
    .B(_15_),
    .Y(_00_[3])
  );
  NAND _64_ (
    .A(reset),
    .B(valid_in),
    .Y(_16_)
  );
  NOR _65_ (
    .A(data_in[4]),
    .B(_16_),
    .Y(_17_)
  );
  NOR _66_ (
    .A(contador[2]),
    .B(_17_),
    .Y(_18_)
  );
  NOR _67_ (
    .A(_08_),
    .B(_16_),
    .Y(_19_)
  );
  NOT _68_ (
    .A(_19_),
    .Y(_20_)
  );
  NAND _69_ (
    .A(data_in[0]),
    .B(_19_),
    .Y(_21_)
  );
  NAND _70_ (
    .A(contador[1]),
    .B(_21_),
    .Y(_22_)
  );
  NOR _71_ (
    .A(_18_),
    .B(_22_),
    .Y(_23_)
  );
  NOR _72_ (
    .A(data_in[2]),
    .B(_20_),
    .Y(_24_)
  );
  NOR _73_ (
    .A(_04_),
    .B(_16_),
    .Y(_25_)
  );
  NOR _74_ (
    .A(contador[2]),
    .B(_25_),
    .Y(_26_)
  );
  NOR _75_ (
    .A(_24_),
    .B(_26_),
    .Y(_27_)
  );
  NOR _76_ (
    .A(contador[1]),
    .B(_27_),
    .Y(_28_)
  );
  NOR _77_ (
    .A(_23_),
    .B(_28_),
    .Y(_29_)
  );
  NOR _78_ (
    .A(_06_),
    .B(_29_),
    .Y(_30_)
  );
  NOR _79_ (
    .A(contador[1]),
    .B(_16_),
    .Y(_31_)
  );
  NOR _80_ (
    .A(_05_),
    .B(contador[2]),
    .Y(_32_)
  );
  NAND _81_ (
    .A(data_in[3]),
    .B(contador[2]),
    .Y(_33_)
  );
  NOT _82_ (
    .A(_33_),
    .Y(_34_)
  );
  NOR _83_ (
    .A(_32_),
    .B(_34_),
    .Y(_35_)
  );
  NAND _84_ (
    .A(_31_),
    .B(_35_),
    .Y(_36_)
  );
  NOR _85_ (
    .A(data_in[5]),
    .B(_16_),
    .Y(_37_)
  );
  NOR _86_ (
    .A(contador[2]),
    .B(_37_),
    .Y(_38_)
  );
  NAND _87_ (
    .A(data_in[1]),
    .B(_19_),
    .Y(_39_)
  );
  NOR _88_ (
    .A(_07_),
    .B(_38_),
    .Y(_40_)
  );
  NAND _89_ (
    .A(_39_),
    .B(_40_),
    .Y(_41_)
  );
  NAND _90_ (
    .A(_36_),
    .B(_41_),
    .Y(_42_)
  );
  NAND _91_ (
    .A(_06_),
    .B(_42_),
    .Y(_43_)
  );
  NOR _92_ (
    .A(contador[3]),
    .B(_03_),
    .Y(_44_)
  );
  NAND _93_ (
    .A(_43_),
    .B(_44_),
    .Y(_45_)
  );
  NOR _94_ (
    .A(_30_),
    .B(_45_),
    .Y(_01_)
  );
  DFF _95_ (
    .C(clk_8f),
    .D(_01_),
    .Q(data_out)
  );
  DFF _96_ (
    .C(clk_8f),
    .D(_00_[0]),
    .Q(contador[0])
  );
  DFF _97_ (
    .C(clk_8f),
    .D(_00_[1]),
    .Q(contador[1])
  );
  DFF _98_ (
    .C(clk_8f),
    .D(_00_[2]),
    .Q(contador[2])
  );
  DFF _99_ (
    .C(clk_8f),
    .D(_00_[3]),
    .Q(contador[3])
  );
endmodule

module phy_tx(reset, clk_8f, clk_2f, clk_f, enable, validin, entrada, salida_ser_lane_0, salida_ser_lane_1);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  input clk_2f;
  input clk_8f;
  input clk_f;
  wire [7:0] data_0_mux;
  wire [7:0] data_1_mux;
  input enable;
  input [3:0] entrada;
  wire [7:0] lane_0;
  wire [7:0] lane_1;
  input reset;
  wire sal0parse;
  wire sal1parse;
  wire [7:0] salida_mux;
  output salida_ser_lane_0;
  output salida_ser_lane_1;
  wire valid_0;
  wire valid_0_mux;
  wire valid_1;
  wire valid_1_mux;
  wire valid_mux;
  input validin;
  NAND _4_ (
    .A(sal0parse),
    .B(reset),
    .Y(_2_)
  );
  NOT _5_ (
    .A(_2_),
    .Y(_0_)
  );
  NAND _6_ (
    .A(reset),
    .B(sal1parse),
    .Y(_3_)
  );
  NOT _7_ (
    .A(_3_),
    .Y(_1_)
  );
  DFF _8_ (
    .C(clk_8f),
    .D(_0_),
    .Q(salida_ser_lane_0)
  );
  DFF _9_ (
    .C(clk_8f),
    .D(_1_),
    .Q(salida_ser_lane_1)
  );
  bs bystripping (
    .clk_2f(clk_2f),
    .data_in(salida_mux),
    .lane_0_cond(lane_0),
    .lane_1_cond(lane_1),
    .reset(reset),
    .valid_0_cond(valid_0),
    .valid_1_cond(valid_1),
    .valid_in(valid_mux)
  );
  gen_clk clks (
    .clk_2f(clk_2f),
    .clk_8f(clk_8f),
    .clk_f(clk_f),
    .enb(enable),
    .rst(reset)
  );
  partoserial linea0 (
    .clk_8f(clk_8f),
    .data_in(lane_0),
    .data_out(sal0parse),
    .reset(reset),
    .valid_in(valid_0)
  );
  partoserial linea1 (
    .clk_8f(clk_8f),
    .data_in(lane_1),
    .data_out(sal1parse),
    .reset(reset),
    .valid_in(valid_1)
  );
  mux muxes (
    .clk(clk_2f),
    .data_in_0(data_0_mux),
    .data_in_1(data_1_mux),
    .data_out(salida_mux),
    .reset_L(reset),
    .valid_in_0(valid_0_mux),
    .valid_in_1(valid_1_mux),
    .valid_out(valid_mux)
  );
endmodule
