/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 5.4.0-6ubuntu1~16.04.4 -O2 -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "serialtopar_synth.v:9" *)
module serialtopar_synth(data_out, valid_out, clk_f, clk_8f, reset_L, data_in);
  (* src = "serialtopar_synth.v:34" *)
  wire _00_;
  (* src = "serialtopar_synth.v:34" *)
  wire [2:0] _01_;
  (* src = "serialtopar_synth.v:24" *)
  wire [7:0] _02_;
  (* src = "serialtopar_synth.v:34" *)
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  (* src = "serialtopar_synth.v:17" *)
  wire active;
  (* src = "serialtopar_synth.v:19" *)
  wire [2:0] bc_cnt;
  (* src = "serialtopar_synth.v:18" *)
  wire [7:0] buffer;
  (* src = "serialtopar_synth.v:13" *)
  input clk_8f;
  (* src = "serialtopar_synth.v:12" *)
  input clk_f;
  (* src = "serialtopar_synth.v:15" *)
  input data_in;
  (* src = "serialtopar_synth.v:10" *)
  output [7:0] data_out;
  (* src = "serialtopar_synth.v:14" *)
  input reset_L;
  (* src = "serialtopar_synth.v:20" *)
  wire [7:0] shift_reg;
  (* src = "serialtopar_synth.v:11" *)
  output valid_out;
  NOT _35_ (
    .A(reset_L),
    .Y(_04_)
  );
  NOR _36_ (
    .A(active),
    .B(bc_cnt[2]),
    .Y(_05_)
  );
  NOR _37_ (
    .A(_05_),
    .B(_04_),
    .Y(_00_)
  );
  NOT _38_ (
    .A(buffer[2]),
    .Y(_06_)
  );
  NOT _39_ (
    .A(buffer[3]),
    .Y(_07_)
  );
  NOR _40_ (
    .A(_07_),
    .B(_06_),
    .Y(_08_)
  );
  NOT _41_ (
    .A(buffer[4]),
    .Y(_09_)
  );
  NOT _42_ (
    .A(buffer[6]),
    .Y(_10_)
  );
  NOR _43_ (
    .A(_10_),
    .B(_09_),
    .Y(_11_)
  );
  NAND _44_ (
    .A(_11_),
    .B(_08_),
    .Y(_12_)
  );
  NOR _45_ (
    .A(buffer[0]),
    .B(data_in),
    .Y(_13_)
  );
  NOT _46_ (
    .A(buffer[1]),
    .Y(_14_)
  );
  NOR _47_ (
    .A(_14_),
    .B(buffer[5]),
    .Y(_15_)
  );
  NAND _48_ (
    .A(_15_),
    .B(_13_),
    .Y(_16_)
  );
  NOR _49_ (
    .A(_16_),
    .B(_12_),
    .Y(_17_)
  );
  NAND _50_ (
    .A(_17_),
    .B(reset_L),
    .Y(_18_)
  );
  NOR _51_ (
    .A(_18_),
    .B(bc_cnt[0]),
    .Y(_01_[0])
  );
  NOT _52_ (
    .A(bc_cnt[0]),
    .Y(_19_)
  );
  NOT _53_ (
    .A(bc_cnt[1]),
    .Y(_20_)
  );
  NAND _54_ (
    .A(_20_),
    .B(_19_),
    .Y(_21_)
  );
  NAND _55_ (
    .A(bc_cnt[1]),
    .B(bc_cnt[0]),
    .Y(_22_)
  );
  NAND _56_ (
    .A(_22_),
    .B(_21_),
    .Y(_23_)
  );
  NOR _57_ (
    .A(_23_),
    .B(_18_),
    .Y(_01_[1])
  );
  NOT _58_ (
    .A(bc_cnt[2]),
    .Y(_24_)
  );
  NOT _59_ (
    .A(_22_),
    .Y(_25_)
  );
  NOR _60_ (
    .A(_25_),
    .B(_24_),
    .Y(_26_)
  );
  NOR _61_ (
    .A(_22_),
    .B(bc_cnt[2]),
    .Y(_27_)
  );
  NOR _62_ (
    .A(_27_),
    .B(_26_),
    .Y(_28_)
  );
  NOR _63_ (
    .A(_28_),
    .B(_18_),
    .Y(_01_[2])
  );
  NOT _64_ (
    .A(valid_out),
    .Y(_29_)
  );
  NAND _65_ (
    .A(_05_),
    .B(_29_),
    .Y(_30_)
  );
  NAND _66_ (
    .A(_30_),
    .B(reset_L),
    .Y(_31_)
  );
  NOR _67_ (
    .A(_31_),
    .B(_17_),
    .Y(_03_)
  );
  NOT _68_ (
    .A(data_in),
    .Y(_32_)
  );
  NOR _69_ (
    .A(_04_),
    .B(_32_),
    .Y(_02_[0])
  );
  NOT _70_ (
    .A(buffer[0]),
    .Y(_33_)
  );
  NOR _71_ (
    .A(_04_),
    .B(_33_),
    .Y(_02_[1])
  );
  NOR _72_ (
    .A(_14_),
    .B(_04_),
    .Y(_02_[2])
  );
  NOR _73_ (
    .A(_06_),
    .B(_04_),
    .Y(_02_[3])
  );
  NOR _74_ (
    .A(_07_),
    .B(_04_),
    .Y(_02_[4])
  );
  NOR _75_ (
    .A(_09_),
    .B(_04_),
    .Y(_02_[5])
  );
  NOT _76_ (
    .A(buffer[5]),
    .Y(_34_)
  );
  NOR _77_ (
    .A(_04_),
    .B(_34_),
    .Y(_02_[6])
  );
  NOR _78_ (
    .A(_10_),
    .B(_04_),
    .Y(_02_[7])
  );
  DFF _79_ (
    .C(clk_f),
    .D(_02_[0]),
    .Q(data_out[0])
  );
  DFF _80_ (
    .C(clk_f),
    .D(_02_[1]),
    .Q(data_out[1])
  );
  DFF _81_ (
    .C(clk_f),
    .D(_02_[2]),
    .Q(data_out[2])
  );
  DFF _82_ (
    .C(clk_f),
    .D(_02_[3]),
    .Q(data_out[3])
  );
  DFF _83_ (
    .C(clk_f),
    .D(_02_[4]),
    .Q(data_out[4])
  );
  DFF _84_ (
    .C(clk_f),
    .D(_02_[5]),
    .Q(data_out[5])
  );
  DFF _85_ (
    .C(clk_f),
    .D(_02_[6]),
    .Q(data_out[6])
  );
  DFF _86_ (
    .C(clk_f),
    .D(_02_[7]),
    .Q(data_out[7])
  );
  DFF _87_ (
    .C(clk_f),
    .D(_03_),
    .Q(valid_out)
  );
  DFF _88_ (
    .C(clk_f),
    .D(_00_),
    .Q(active)
  );
  DFF _89_ (
    .C(clk_f),
    .D(_01_[0]),
    .Q(bc_cnt[0])
  );
  DFF _90_ (
    .C(clk_f),
    .D(_01_[1]),
    .Q(bc_cnt[1])
  );
  DFF _91_ (
    .C(clk_f),
    .D(_01_[2]),
    .Q(bc_cnt[2])
  );
  DFF _92_ (
    .C(clk_8f),
    .D(_02_[0]),
    .Q(buffer[0])
  );
  DFF _93_ (
    .C(clk_8f),
    .D(_02_[1]),
    .Q(buffer[1])
  );
  DFF _94_ (
    .C(clk_8f),
    .D(_02_[2]),
    .Q(buffer[2])
  );
  DFF _95_ (
    .C(clk_8f),
    .D(_02_[3]),
    .Q(buffer[3])
  );
  DFF _96_ (
    .C(clk_8f),
    .D(_02_[4]),
    .Q(buffer[4])
  );
  DFF _97_ (
    .C(clk_8f),
    .D(_02_[5]),
    .Q(buffer[5])
  );
  DFF _98_ (
    .C(clk_8f),
    .D(_02_[6]),
    .Q(buffer[6])
  );
  assign shift_reg = { buffer[6:0], data_in };
endmodule
