/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 5.4.0-6ubuntu1~16.04.4 -O2 -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "serialtopar_synth.v:9" *)
module serialtopar_synth(data_out, valid_out, clk_f, clk_8f, reset_L, data_in);
  (* src = "serialtopar_synth.v:18" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] buffer;
  (* src = "serialtopar_synth.v:13" *)
  input clk_8f;
  (* src = "serialtopar_synth.v:12" *)
  input clk_f;
  (* src = "serialtopar_synth.v:15" *)
  input data_in;
  (* src = "serialtopar_synth.v:10" *)
  output [7:0] data_out;
  (* src = "serialtopar_synth.v:14" *)
  input reset_L;
  (* src = "serialtopar_synth.v:20" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] shift_reg;
  (* src = "serialtopar_synth.v:11" *)
  output valid_out;
  assign data_out = 8'b00000000;
  assign shift_reg = { data_in, buffer[7:1] };
  assign valid_out = 1'b0;
endmodule
