/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 5.4.0-6ubuntu1~16.04.4 -O2 -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "mux_synth.v:9" *)
module mux_synth(data_out, valid_out, clk, reset_L, valid_in_0, data_in_0, valid_in_1, data_in_1);
  (* src = "mux_synth.v:71" *)
  wire [7:0] _00_;
  (* src = "mux_synth.v:71" *)
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  (* src = "mux_synth.v:12" *)
  input clk;
  (* src = "mux_synth.v:15" *)
  input [7:0] data_in_0;
  (* src = "mux_synth.v:17" *)
  input [7:0] data_in_1;
  (* src = "mux_synth.v:10" *)
  output [7:0] data_out;
  (* src = "mux_synth.v:13" *)
  input reset_L;
  (* src = "mux_synth.v:14" *)
  input valid_in_0;
  (* src = "mux_synth.v:16" *)
  input valid_in_1;
  (* src = "mux_synth.v:11" *)
  output valid_out;
  NOT _16_ (
    .A(reset_L),
    .Y(_02_)
  );
  NOR _17_ (
    .A(valid_in_1),
    .B(valid_in_0),
    .Y(_03_)
  );
  NOR _18_ (
    .A(_03_),
    .B(_02_),
    .Y(_01_)
  );
  NOT _19_ (
    .A(data_in_0[0]),
    .Y(_04_)
  );
  NOT _20_ (
    .A(valid_in_0),
    .Y(_05_)
  );
  NOT _21_ (
    .A(valid_in_1),
    .Y(_06_)
  );
  NAND _22_ (
    .A(_06_),
    .B(_05_),
    .Y(_07_)
  );
  NAND _23_ (
    .A(_07_),
    .B(reset_L),
    .Y(_08_)
  );
  NOR _24_ (
    .A(_08_),
    .B(_04_),
    .Y(_00_[0])
  );
  NOT _25_ (
    .A(data_in_0[1]),
    .Y(_09_)
  );
  NOR _26_ (
    .A(_08_),
    .B(_09_),
    .Y(_00_[1])
  );
  NOT _27_ (
    .A(data_in_0[2]),
    .Y(_10_)
  );
  NOR _28_ (
    .A(_08_),
    .B(_10_),
    .Y(_00_[2])
  );
  NOT _29_ (
    .A(data_in_0[3]),
    .Y(_11_)
  );
  NOR _30_ (
    .A(_08_),
    .B(_11_),
    .Y(_00_[3])
  );
  NOT _31_ (
    .A(data_in_0[4]),
    .Y(_12_)
  );
  NOR _32_ (
    .A(_08_),
    .B(_12_),
    .Y(_00_[4])
  );
  NOT _33_ (
    .A(data_in_0[5]),
    .Y(_13_)
  );
  NOR _34_ (
    .A(_08_),
    .B(_13_),
    .Y(_00_[5])
  );
  NOT _35_ (
    .A(data_in_0[6]),
    .Y(_14_)
  );
  NOR _36_ (
    .A(_08_),
    .B(_14_),
    .Y(_00_[6])
  );
  NOT _37_ (
    .A(data_in_0[7]),
    .Y(_15_)
  );
  NOR _38_ (
    .A(_08_),
    .B(_15_),
    .Y(_00_[7])
  );
  DFF _39_ (
    .C(clk),
    .D(_00_[0]),
    .Q(data_out[0])
  );
  DFF _40_ (
    .C(clk),
    .D(_00_[1]),
    .Q(data_out[1])
  );
  DFF _41_ (
    .C(clk),
    .D(_00_[2]),
    .Q(data_out[2])
  );
  DFF _42_ (
    .C(clk),
    .D(_00_[3]),
    .Q(data_out[3])
  );
  DFF _43_ (
    .C(clk),
    .D(_00_[4]),
    .Q(data_out[4])
  );
  DFF _44_ (
    .C(clk),
    .D(_00_[5]),
    .Q(data_out[5])
  );
  DFF _45_ (
    .C(clk),
    .D(_00_[6]),
    .Q(data_out[6])
  );
  DFF _46_ (
    .C(clk),
    .D(_00_[7]),
    .Q(data_out[7])
  );
  DFF _47_ (
    .C(clk),
    .D(_01_),
    .Q(valid_out)
  );
endmodule
