/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 5.4.0-6ubuntu1~16.04.4 -O2 -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "mux_synth.v:9" *)
module mux_synth(data_out, valid_out, clk, reset_L, valid_in_0, data_in_0, valid_in_1, data_in_1);
  (* src = "mux_synth.v:68" *)
  wire [1:0] _000_;
  (* src = "mux_synth.v:68" *)
  wire [7:0] _001_;
  (* src = "mux_synth.v:68" *)
  wire _002_;
  (* src = "mux_synth.v:68" *)
  wire _003_;
  (* src = "mux_synth.v:68" *)
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  (* src = "mux_synth.v:12" *)
  input clk;
  (* src = "mux_synth.v:20" *)
  wire [1:0] cntr_wait_cyc;
  (* src = "mux_synth.v:15" *)
  input [7:0] data_in_0;
  (* src = "mux_synth.v:17" *)
  input [7:0] data_in_1;
  (* src = "mux_synth.v:10" *)
  output [7:0] data_out;
  (* src = "mux_synth.v:13" *)
  input reset_L;
  (* src = "mux_synth.v:19" *)
  wire selector;
  (* src = "mux_synth.v:19" *)
  wire sync;
  (* src = "mux_synth.v:14" *)
  input valid_in_0;
  (* src = "mux_synth.v:16" *)
  input valid_in_1;
  (* src = "mux_synth.v:11" *)
  output valid_out;
  NOR _091_ (
    .A(_038_),
    .B(_037_),
    .Y(_002_)
  );
  NOR _092_ (
    .A(valid_in_1),
    .B(valid_in_0),
    .Y(_039_)
  );
  NAND _093_ (
    .A(_039_),
    .B(reset_L),
    .Y(_040_)
  );
  NAND _094_ (
    .A(_040_),
    .B(cntr_wait_cyc[0]),
    .Y(_041_)
  );
  NOR _095_ (
    .A(cntr_wait_cyc[0]),
    .B(_038_),
    .Y(_042_)
  );
  NOT _096_ (
    .A(valid_in_0),
    .Y(_043_)
  );
  NOT _097_ (
    .A(valid_in_1),
    .Y(_044_)
  );
  NAND _098_ (
    .A(_044_),
    .B(_043_),
    .Y(_045_)
  );
  NOR _099_ (
    .A(_045_),
    .B(cntr_wait_cyc[1]),
    .Y(_046_)
  );
  NAND _100_ (
    .A(_046_),
    .B(_042_),
    .Y(_047_)
  );
  NAND _101_ (
    .A(_047_),
    .B(_041_),
    .Y(_000_[0])
  );
  NOT _102_ (
    .A(cntr_wait_cyc[1]),
    .Y(_048_)
  );
  NOR _103_ (
    .A(_040_),
    .B(_048_),
    .Y(_049_)
  );
  NOT _104_ (
    .A(cntr_wait_cyc[0]),
    .Y(_050_)
  );
  NAND _105_ (
    .A(_050_),
    .B(reset_L),
    .Y(_051_)
  );
  NAND _106_ (
    .A(_040_),
    .B(_048_),
    .Y(_052_)
  );
  NAND _107_ (
    .A(_052_),
    .B(_051_),
    .Y(_053_)
  );
  NOR _108_ (
    .A(_053_),
    .B(_049_),
    .Y(_000_[1])
  );
  NAND _109_ (
    .A(reset_L),
    .B(sync),
    .Y(_054_)
  );
  NOR _110_ (
    .A(_054_),
    .B(_039_),
    .Y(_004_)
  );
  NOT _111_ (
    .A(_004_),
    .Y(_055_)
  );
  NAND _112_ (
    .A(_042_),
    .B(cntr_wait_cyc[1]),
    .Y(_056_)
  );
  NAND _113_ (
    .A(_056_),
    .B(_055_),
    .Y(_003_)
  );
  NAND _114_ (
    .A(valid_in_1),
    .B(valid_in_0),
    .Y(_057_)
  );
  NOR _115_ (
    .A(_057_),
    .B(_054_),
    .Y(_058_)
  );
  NOR _116_ (
    .A(data_in_1[0]),
    .B(_037_),
    .Y(_059_)
  );
  NOR _117_ (
    .A(data_in_0[0]),
    .B(selector),
    .Y(_060_)
  );
  NOR _118_ (
    .A(_060_),
    .B(_059_),
    .Y(_061_)
  );
  NAND _119_ (
    .A(_061_),
    .B(_058_),
    .Y(_062_)
  );
  NAND _120_ (
    .A(data_in_1[0]),
    .B(_043_),
    .Y(_063_)
  );
  NAND _121_ (
    .A(data_in_0[0]),
    .B(_044_),
    .Y(_064_)
  );
  NAND _122_ (
    .A(_064_),
    .B(_063_),
    .Y(_065_)
  );
  NAND _123_ (
    .A(_065_),
    .B(_004_),
    .Y(_066_)
  );
  NAND _124_ (
    .A(_066_),
    .B(_062_),
    .Y(_001_[0])
  );
  NOR _125_ (
    .A(data_in_0[1]),
    .B(selector),
    .Y(_067_)
  );
  NOR _126_ (
    .A(data_in_1[1]),
    .B(_037_),
    .Y(_068_)
  );
  NOR _127_ (
    .A(_068_),
    .B(_067_),
    .Y(_069_)
  );
  NAND _128_ (
    .A(_069_),
    .B(_058_),
    .Y(_070_)
  );
  NAND _129_ (
    .A(data_in_1[1]),
    .B(_043_),
    .Y(_071_)
  );
  NAND _130_ (
    .A(data_in_0[1]),
    .B(_044_),
    .Y(_072_)
  );
  NAND _131_ (
    .A(_072_),
    .B(_071_),
    .Y(_073_)
  );
  NAND _132_ (
    .A(_073_),
    .B(_004_),
    .Y(_074_)
  );
  NAND _133_ (
    .A(_074_),
    .B(_070_),
    .Y(_001_[1])
  );
  NOR _134_ (
    .A(data_in_1[2]),
    .B(_037_),
    .Y(_075_)
  );
  NOR _135_ (
    .A(data_in_0[2]),
    .B(selector),
    .Y(_076_)
  );
  NOR _136_ (
    .A(_076_),
    .B(_075_),
    .Y(_077_)
  );
  NAND _137_ (
    .A(_077_),
    .B(_058_),
    .Y(_078_)
  );
  NAND _138_ (
    .A(data_in_1[2]),
    .B(_043_),
    .Y(_079_)
  );
  NAND _139_ (
    .A(data_in_0[2]),
    .B(_044_),
    .Y(_080_)
  );
  NAND _140_ (
    .A(_080_),
    .B(_079_),
    .Y(_081_)
  );
  NAND _141_ (
    .A(_081_),
    .B(_004_),
    .Y(_082_)
  );
  NAND _142_ (
    .A(_082_),
    .B(_078_),
    .Y(_001_[2])
  );
  NOR _143_ (
    .A(data_in_0[3]),
    .B(selector),
    .Y(_083_)
  );
  NOR _144_ (
    .A(data_in_1[3]),
    .B(_037_),
    .Y(_084_)
  );
  NOR _145_ (
    .A(_084_),
    .B(_083_),
    .Y(_085_)
  );
  NAND _146_ (
    .A(_085_),
    .B(_058_),
    .Y(_086_)
  );
  NAND _147_ (
    .A(data_in_1[3]),
    .B(_043_),
    .Y(_087_)
  );
  NAND _148_ (
    .A(data_in_0[3]),
    .B(_044_),
    .Y(_088_)
  );
  NAND _149_ (
    .A(_088_),
    .B(_087_),
    .Y(_089_)
  );
  NAND _150_ (
    .A(_089_),
    .B(_004_),
    .Y(_090_)
  );
  NAND _151_ (
    .A(_090_),
    .B(_086_),
    .Y(_001_[3])
  );
  NOR _152_ (
    .A(data_in_1[4]),
    .B(_037_),
    .Y(_005_)
  );
  NOR _153_ (
    .A(data_in_0[4]),
    .B(selector),
    .Y(_006_)
  );
  NOR _154_ (
    .A(_006_),
    .B(_005_),
    .Y(_007_)
  );
  NAND _155_ (
    .A(_007_),
    .B(_058_),
    .Y(_008_)
  );
  NAND _156_ (
    .A(data_in_1[4]),
    .B(_043_),
    .Y(_009_)
  );
  NAND _157_ (
    .A(data_in_0[4]),
    .B(_044_),
    .Y(_010_)
  );
  NAND _158_ (
    .A(_010_),
    .B(_009_),
    .Y(_011_)
  );
  NAND _159_ (
    .A(_011_),
    .B(_004_),
    .Y(_012_)
  );
  NAND _160_ (
    .A(_012_),
    .B(_008_),
    .Y(_001_[4])
  );
  NOR _161_ (
    .A(data_in_0[5]),
    .B(selector),
    .Y(_013_)
  );
  NOR _162_ (
    .A(data_in_1[5]),
    .B(_037_),
    .Y(_014_)
  );
  NOR _163_ (
    .A(_014_),
    .B(_013_),
    .Y(_015_)
  );
  NAND _164_ (
    .A(_015_),
    .B(_058_),
    .Y(_016_)
  );
  NAND _165_ (
    .A(data_in_1[5]),
    .B(_043_),
    .Y(_017_)
  );
  NAND _166_ (
    .A(data_in_0[5]),
    .B(_044_),
    .Y(_018_)
  );
  NAND _167_ (
    .A(_018_),
    .B(_017_),
    .Y(_019_)
  );
  NAND _168_ (
    .A(_019_),
    .B(_004_),
    .Y(_020_)
  );
  NAND _169_ (
    .A(_020_),
    .B(_016_),
    .Y(_001_[5])
  );
  NOR _170_ (
    .A(data_in_1[6]),
    .B(_037_),
    .Y(_021_)
  );
  NOR _171_ (
    .A(data_in_0[6]),
    .B(selector),
    .Y(_022_)
  );
  NOR _172_ (
    .A(_022_),
    .B(_021_),
    .Y(_023_)
  );
  NAND _173_ (
    .A(_023_),
    .B(_058_),
    .Y(_024_)
  );
  NAND _174_ (
    .A(data_in_1[6]),
    .B(_043_),
    .Y(_025_)
  );
  NAND _175_ (
    .A(data_in_0[6]),
    .B(_044_),
    .Y(_026_)
  );
  NAND _176_ (
    .A(_026_),
    .B(_025_),
    .Y(_027_)
  );
  NAND _177_ (
    .A(_027_),
    .B(_004_),
    .Y(_028_)
  );
  NAND _178_ (
    .A(_028_),
    .B(_024_),
    .Y(_001_[6])
  );
  NAND _179_ (
    .A(data_in_1[7]),
    .B(_043_),
    .Y(_029_)
  );
  NAND _180_ (
    .A(data_in_0[7]),
    .B(_044_),
    .Y(_030_)
  );
  NAND _181_ (
    .A(_030_),
    .B(_029_),
    .Y(_031_)
  );
  NAND _182_ (
    .A(_031_),
    .B(_004_),
    .Y(_032_)
  );
  NAND _183_ (
    .A(data_in_0[7]),
    .B(_037_),
    .Y(_033_)
  );
  NAND _184_ (
    .A(data_in_1[7]),
    .B(selector),
    .Y(_034_)
  );
  NAND _185_ (
    .A(_034_),
    .B(_033_),
    .Y(_035_)
  );
  NAND _186_ (
    .A(_035_),
    .B(_058_),
    .Y(_036_)
  );
  NAND _187_ (
    .A(_036_),
    .B(_032_),
    .Y(_001_[7])
  );
  NOT _188_ (
    .A(selector),
    .Y(_037_)
  );
  NOT _189_ (
    .A(reset_L),
    .Y(_038_)
  );
  DFF _190_ (
    .C(clk),
    .D(_001_[0]),
    .Q(data_out[0])
  );
  DFF _191_ (
    .C(clk),
    .D(_001_[1]),
    .Q(data_out[1])
  );
  DFF _192_ (
    .C(clk),
    .D(_001_[2]),
    .Q(data_out[2])
  );
  DFF _193_ (
    .C(clk),
    .D(_001_[3]),
    .Q(data_out[3])
  );
  DFF _194_ (
    .C(clk),
    .D(_001_[4]),
    .Q(data_out[4])
  );
  DFF _195_ (
    .C(clk),
    .D(_001_[5]),
    .Q(data_out[5])
  );
  DFF _196_ (
    .C(clk),
    .D(_001_[6]),
    .Q(data_out[6])
  );
  DFF _197_ (
    .C(clk),
    .D(_001_[7]),
    .Q(data_out[7])
  );
  DFF _198_ (
    .C(clk),
    .D(_004_),
    .Q(valid_out)
  );
  DFF _199_ (
    .C(clk),
    .D(_002_),
    .Q(selector)
  );
  DFF _200_ (
    .C(clk),
    .D(_003_),
    .Q(sync)
  );
  DFF _201_ (
    .C(clk),
    .D(_000_[0]),
    .Q(cntr_wait_cyc[0])
  );
  DFF _202_ (
    .C(clk),
    .D(_000_[1]),
    .Q(cntr_wait_cyc[1])
  );
endmodule
