/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

module byte_unstripping(data_demux, valid_demux, clk_f, clk_2f, reset_L, data_stripe_0, data_stripe_1, valid_stripe_0, valid_stripe_1);
  wire [7:0] _000_;
  wire [7:0] _001_;
  wire [7:0] _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  input clk_2f;
  input clk_f;
  output [7:0] data_demux;
  input [7:0] data_stripe_0;
  input [7:0] data_stripe_1;
  wire [7:0] data_validated_0;
  wire [7:0] data_validated_1;
  input reset_L;
  output valid_demux;
  input valid_stripe_0;
  input valid_stripe_1;
  NOT _038_ (
    .A(valid_stripe_1),
    .Y(_010_)
  );
  NOT _039_ (
    .A(reset_L),
    .Y(_018_)
  );
  NOR _040_ (
    .A(_018_),
    .B(_010_),
    .Y(_011_)
  );
  NAND _041_ (
    .A(_011_),
    .B(data_stripe_1[0]),
    .Y(_012_)
  );
  NAND _042_ (
    .A(reset_L),
    .B(valid_stripe_1),
    .Y(_013_)
  );
  NAND _043_ (
    .A(_013_),
    .B(data_validated_0[7]),
    .Y(_014_)
  );
  NAND _044_ (
    .A(_014_),
    .B(_012_),
    .Y(_002_[0])
  );
  NAND _045_ (
    .A(_011_),
    .B(data_stripe_1[1]),
    .Y(_015_)
  );
  NAND _046_ (
    .A(_015_),
    .B(_014_),
    .Y(_002_[1])
  );
  NAND _047_ (
    .A(_011_),
    .B(data_stripe_1[2]),
    .Y(_016_)
  );
  NAND _048_ (
    .A(_016_),
    .B(_014_),
    .Y(_002_[2])
  );
  NAND _049_ (
    .A(_011_),
    .B(data_stripe_1[3]),
    .Y(_017_)
  );
  NAND _050_ (
    .A(_017_),
    .B(_014_),
    .Y(_002_[3])
  );
  NAND _051_ (
    .A(_011_),
    .B(data_stripe_1[4]),
    .Y(_019_)
  );
  NAND _052_ (
    .A(_019_),
    .B(_014_),
    .Y(_002_[4])
  );
  NAND _053_ (
    .A(_011_),
    .B(data_stripe_1[5]),
    .Y(_020_)
  );
  NAND _054_ (
    .A(_020_),
    .B(_014_),
    .Y(_002_[5])
  );
  NAND _055_ (
    .A(_011_),
    .B(data_stripe_1[6]),
    .Y(_021_)
  );
  NAND _056_ (
    .A(_021_),
    .B(_014_),
    .Y(_002_[6])
  );
  NAND _057_ (
    .A(_011_),
    .B(data_stripe_1[7]),
    .Y(_022_)
  );
  NAND _058_ (
    .A(_022_),
    .B(_014_),
    .Y(_002_[7])
  );
  NOT _059_ (
    .A(valid_stripe_0),
    .Y(_023_)
  );
  NOR _060_ (
    .A(_023_),
    .B(_018_),
    .Y(_024_)
  );
  NAND _061_ (
    .A(_024_),
    .B(data_stripe_0[0]),
    .Y(_025_)
  );
  NAND _062_ (
    .A(valid_stripe_0),
    .B(reset_L),
    .Y(_026_)
  );
  NAND _063_ (
    .A(_026_),
    .B(data_validated_0[7]),
    .Y(_027_)
  );
  NAND _064_ (
    .A(_027_),
    .B(_025_),
    .Y(_001_[0])
  );
  NAND _065_ (
    .A(_024_),
    .B(data_stripe_0[1]),
    .Y(_028_)
  );
  NAND _066_ (
    .A(_028_),
    .B(_027_),
    .Y(_001_[1])
  );
  NAND _067_ (
    .A(_024_),
    .B(data_stripe_0[2]),
    .Y(_029_)
  );
  NAND _068_ (
    .A(_029_),
    .B(_027_),
    .Y(_001_[2])
  );
  NAND _069_ (
    .A(_024_),
    .B(data_stripe_0[3]),
    .Y(_030_)
  );
  NAND _070_ (
    .A(_030_),
    .B(_027_),
    .Y(_001_[3])
  );
  NAND _071_ (
    .A(_024_),
    .B(data_stripe_0[4]),
    .Y(_031_)
  );
  NAND _072_ (
    .A(_031_),
    .B(_027_),
    .Y(_001_[4])
  );
  NAND _073_ (
    .A(_024_),
    .B(data_stripe_0[5]),
    .Y(_032_)
  );
  NAND _074_ (
    .A(_032_),
    .B(_027_),
    .Y(_001_[5])
  );
  NAND _075_ (
    .A(_024_),
    .B(data_stripe_0[6]),
    .Y(_033_)
  );
  NAND _076_ (
    .A(_033_),
    .B(_027_),
    .Y(_001_[6])
  );
  NAND _077_ (
    .A(_024_),
    .B(data_stripe_0[7]),
    .Y(_034_)
  );
  NAND _078_ (
    .A(_034_),
    .B(_027_),
    .Y(_001_[7])
  );
  NOT _079_ (
    .A(valid_demux),
    .Y(_035_)
  );
  NAND _080_ (
    .A(_035_),
    .B(data_demux[0]),
    .Y(_036_)
  );
  NAND _081_ (
    .A(valid_demux),
    .B(data_validated_0[7]),
    .Y(_037_)
  );
  NAND _082_ (
    .A(_037_),
    .B(_036_),
    .Y(_000_[0])
  );
  NAND _083_ (
    .A(data_demux[1]),
    .B(_035_),
    .Y(_003_)
  );
  NAND _084_ (
    .A(_003_),
    .B(_037_),
    .Y(_000_[1])
  );
  NAND _085_ (
    .A(data_demux[2]),
    .B(_035_),
    .Y(_004_)
  );
  NAND _086_ (
    .A(_004_),
    .B(_037_),
    .Y(_000_[2])
  );
  NAND _087_ (
    .A(data_demux[3]),
    .B(_035_),
    .Y(_005_)
  );
  NAND _088_ (
    .A(_005_),
    .B(_037_),
    .Y(_000_[3])
  );
  NAND _089_ (
    .A(data_demux[4]),
    .B(_035_),
    .Y(_006_)
  );
  NAND _090_ (
    .A(_006_),
    .B(_037_),
    .Y(_000_[4])
  );
  NAND _091_ (
    .A(data_demux[5]),
    .B(_035_),
    .Y(_007_)
  );
  NAND _092_ (
    .A(_007_),
    .B(_037_),
    .Y(_000_[5])
  );
  NAND _093_ (
    .A(data_demux[6]),
    .B(_035_),
    .Y(_008_)
  );
  NAND _094_ (
    .A(_008_),
    .B(_037_),
    .Y(_000_[6])
  );
  NAND _095_ (
    .A(data_demux[7]),
    .B(_035_),
    .Y(_009_)
  );
  NAND _096_ (
    .A(_009_),
    .B(_037_),
    .Y(_000_[7])
  );
  DFF _097_ (
    .C(clk_2f),
    .D(_000_[0]),
    .Q(data_demux[0])
  );
  DFF _098_ (
    .C(clk_2f),
    .D(_000_[1]),
    .Q(data_demux[1])
  );
  DFF _099_ (
    .C(clk_2f),
    .D(_000_[2]),
    .Q(data_demux[2])
  );
  DFF _100_ (
    .C(clk_2f),
    .D(_000_[3]),
    .Q(data_demux[3])
  );
  DFF _101_ (
    .C(clk_2f),
    .D(_000_[4]),
    .Q(data_demux[4])
  );
  DFF _102_ (
    .C(clk_2f),
    .D(_000_[5]),
    .Q(data_demux[5])
  );
  DFF _103_ (
    .C(clk_2f),
    .D(_000_[6]),
    .Q(data_demux[6])
  );
  DFF _104_ (
    .C(clk_2f),
    .D(_000_[7]),
    .Q(data_demux[7])
  );
  DFF _105_ (
    .C(clk_2f),
    .D(_001_[0]),
    .Q(data_validated_0[7])
  );
  DFF _106_ (
    .C(clk_2f),
    .D(_001_[1]),
    .Q(data_validated_0[7])
  );
  DFF _107_ (
    .C(clk_2f),
    .D(_001_[2]),
    .Q(data_validated_0[7])
  );
  DFF _108_ (
    .C(clk_2f),
    .D(_001_[3]),
    .Q(data_validated_0[7])
  );
  DFF _109_ (
    .C(clk_2f),
    .D(_001_[4]),
    .Q(data_validated_0[7])
  );
  DFF _110_ (
    .C(clk_2f),
    .D(_001_[5]),
    .Q(data_validated_0[7])
  );
  DFF _111_ (
    .C(clk_2f),
    .D(_001_[6]),
    .Q(data_validated_0[7])
  );
  DFF _112_ (
    .C(clk_2f),
    .D(_001_[7]),
    .Q(data_validated_0[7])
  );
  DFF _113_ (
    .C(clk_2f),
    .D(_002_[0]),
    .Q(data_validated_0[7])
  );
  DFF _114_ (
    .C(clk_2f),
    .D(_002_[1]),
    .Q(data_validated_0[7])
  );
  DFF _115_ (
    .C(clk_2f),
    .D(_002_[2]),
    .Q(data_validated_0[7])
  );
  DFF _116_ (
    .C(clk_2f),
    .D(_002_[3]),
    .Q(data_validated_0[7])
  );
  DFF _117_ (
    .C(clk_2f),
    .D(_002_[4]),
    .Q(data_validated_0[7])
  );
  DFF _118_ (
    .C(clk_2f),
    .D(_002_[5]),
    .Q(data_validated_0[7])
  );
  DFF _119_ (
    .C(clk_2f),
    .D(_002_[6]),
    .Q(data_validated_0[7])
  );
  DFF _120_ (
    .C(clk_2f),
    .D(_002_[7]),
    .Q(data_validated_0[7])
  );
  \$_DLATCH_P_  _121_ (
    .D(1'b0),
    .E(_018_),
    .Q(data_validated_0[7])
  );
  assign data_validated_0[6:0] = { data_validated_0[7], data_validated_0[7], data_validated_0[7], data_validated_0[7], data_validated_0[7], data_validated_0[7], data_validated_0[7] };
  assign data_validated_1 = { data_validated_0[7], data_validated_0[7], data_validated_0[7], data_validated_0[7], data_validated_0[7], data_validated_0[7], data_validated_0[7], data_validated_0[7] };
endmodule
