/* Generated by Yosys 0.8 (git sha1 UNKNOWN, clang 6.0.0-1ubuntu2 -fPIC -Os) */
`include "./CMOS/cmos_cells.v"

module gen_clkSynth(clk_8f, rst, enb, clk_2f, clk_f);
  wire _00_;
  wire _01_;
  wire [1:0] _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  output clk_2f;
  input clk_8f;
  output clk_f;
  wire [0:1] counter;
  input enb;
  input rst;
  NOT _20_ (
    .A(rst),
    .Y(_03_)
  );
  NOT _21_ (
    .A(counter[0]),
    .Y(_04_)
  );
  NAND _22_ (
    .A(enb),
    .B(counter[1]),
    .Y(_05_)
  );
  NOT _23_ (
    .A(_05_),
    .Y(_06_)
  );
  NAND _24_ (
    .A(counter[0]),
    .B(_06_),
    .Y(_07_)
  );
  NOR _25_ (
    .A(clk_2f),
    .B(_07_),
    .Y(_08_)
  );
  NOR _26_ (
    .A(clk_f),
    .B(_08_),
    .Y(_09_)
  );
  NAND _27_ (
    .A(clk_f),
    .B(_08_),
    .Y(_10_)
  );
  NAND _28_ (
    .A(_03_),
    .B(_10_),
    .Y(_11_)
  );
  NOR _29_ (
    .A(_09_),
    .B(_11_),
    .Y(_01_)
  );
  NAND _30_ (
    .A(clk_2f),
    .B(_07_),
    .Y(_12_)
  );
  NOT _31_ (
    .A(_12_),
    .Y(_13_)
  );
  NOR _32_ (
    .A(_08_),
    .B(_13_),
    .Y(_14_)
  );
  NOR _33_ (
    .A(rst),
    .B(_14_),
    .Y(_00_)
  );
  NOR _34_ (
    .A(enb),
    .B(counter[1]),
    .Y(_15_)
  );
  NOT _35_ (
    .A(_15_),
    .Y(_16_)
  );
  NAND _36_ (
    .A(_05_),
    .B(_16_),
    .Y(_17_)
  );
  NAND _37_ (
    .A(_03_),
    .B(_17_),
    .Y(_02_[0])
  );
  NAND _38_ (
    .A(_04_),
    .B(_05_),
    .Y(_18_)
  );
  NAND _39_ (
    .A(_07_),
    .B(_18_),
    .Y(_19_)
  );
  NAND _40_ (
    .A(_03_),
    .B(_19_),
    .Y(_02_[1])
  );
  DFF _41_ (
    .C(clk_8f),
    .D(_00_),
    .Q(clk_2f)
  );
  DFF _42_ (
    .C(clk_8f),
    .D(_01_),
    .Q(clk_f)
  );
  DFF _43_ (
    .C(clk_8f),
    .D(_02_[0]),
    .Q(counter[1])
  );
  DFF _44_ (
    .C(clk_8f),
    .D(_02_[1]),
    .Q(counter[0])
  );
endmodule
